### ISSUE TITLE
[ENH, BUG] BIDS Standard Template Coordinate Frame Definition

### ISSUE THREAD

**Issue by alexrockhill** [bids-standard/bids-specification#1025]
In trying to support the BIDS Standard Template coordinate frames in `mne-bids`, I've run into a few issues:

- Most importantly, what is the coordinate frame of standard template channel locations? The space is specified based on an atlas T1w-type image but it is not clear whether the channels are to be in Freesurfer `surface RAS`, `voxels`, `scanner RAS` or some other coordinate frame.
- Most of the links are fairly straightforward to find the atlas image but a few are not: `IXI549Space` (https://brain-development.org/ ) for instance only allows you to download all 549 T1 images, which is amazing data availability but not very helpful for defining the coordinate frame. `NIHPD`, on the other hand, has multiple allowable T1 images.

The idea with `mne-bids` is to read an electrophysiology image file in a template space and have it properly defined (some progress is here https://github.com/mne-tools/mne-bids/pull/982 but requires a lot of work for the user to find the fiducials of the atlas image when ideally that would just be done once). The issue is that we don't know in which coordinate frame the channels are stored, and, even if we did, we couldn't define the `head` coordinate frame used by MNE internally based on the nasion and left and right pre-auricular points without the T1 image defining the space since a few spaces are inaccessible or ambiguous. Ideally the coordinate frame (e.g. `voxels`) would be clearly specified and there would be a repository of T1 images and even more ideally their sidecar files with `AnatomicalLandmarkCoordiantes` in them.

Does it sound reasonable to insist that template coordinates be in `voxel` or `scanner RAS`?

And is there someone with a repository of all these atlases?

**Comment by alexrockhill** [comment]
We could store the T1 atlases and fiducials in `mne-bids` but it would probably be better to store them this repository

**Comment by alexrockhill** [comment]
Ok I went through all the spaces and I think I found a T1 for all of them but the only note is that the UNCInfant neonates, 1 year and 2 year olds are not affine registered so they have different scales. Not sure how much this matters for their use but it does make it difficult to define a single coordinate frame in terms of fiducial points.

**Comment by alexrockhill** [comment]
Ok I did all the templates, I think they're right. They're too large for GitHub though. Maybe we'll just store the fiducials in `mne-bids` but it would be nice to have a repository of all the template T1s somewhere for people to be able to use them easier https://drive.google.com/drive/folders/1rN-Rb7D6ZTyVKOc2WZ-AM3f3dspIhZtQ?usp=sharing

**Comment by sappelhoff** [comment]
Adding the "Template Based Coordinate Systems" happened back in the Google Doc days, and the info was then migrated here when we switched to GitHub. Some information can be found in this thread: https://groups.google.com/g/bids-discussion/c/DdkxqgikwiI/m/Dju4zmbEBwAJ

The initial suggestions was by Chris G.:

> I recommend that in the upcoming iEEG spec coordinates would be expressed in template space (using mm as units and one of the keywords above), particular scan space (using voxels as units and with relative path to the corresponding nifti file), or photograph (using pixels as units and with relative path to the corresponding photograph file).

Does that help in any way?

> Maybe we'll just store the fiducials in mne-bids but it would be nice to have a repository of all the template T1s somewhere for people to be able to use them easier https://drive.google.com/drive/folders/1rN-Rb7D6ZTyVKOc2WZ-AM3f3dspIhZtQ?usp=sharing

if other people agree this is helpful to store, perhaps we could host them on https://gin.g-node.org/ and link to that from the spec. Would we have all required licenses for that? If yes, we could create a "BIDS" user on GIN to do the uploading.

**Comment by alexrockhill** [comment]
It would be nice to have some consensus that this is the preferred specification for template coordinate systems.  @choldgraf, @dorahermes, @robertoostenveld, @adam2392, @agramfort @libertyh does that seem reasoable?

**Comment by choldgraf** [comment]
I have no strong opinions here, and defer to what @alexrockhill, @sappelhoff, and the others think is best.

**Comment by satra** [comment]
@alexrockhill - perhaps https://www.templateflow.org/ can help.

**Comment by alexrockhill** [comment]
> @alexrockhill - perhaps https://www.templateflow.org/ can help.

Awesome, that looks like it might be just the ticket! I'll have to check that it has all the BIDS standard templates.

**Comment by alexrockhill** [comment]
It looks like all the following templates are in BIDS but not `templateflow`: `ICBM452AirSpace`, `ICBM452Warp5Space`, `IXI549Space` `fsaverageSym`, `MNI152NLin2009bSym`, `NIHPD`, `OASIS30Atropos` and `Talairach`. That's about half of the total templates but there is a nice fetcher so it might be worth adding by PRs. From just checking `UNCInfant` it does look like the `AnatomicalLandmarkCoordinates` I found previously look reasonable. Those might be nice to add as well.

**Comment by sappelhoff** [comment]
cc @oesteban who tends to know about these things

**Comment by alexrockhill** [comment]
So it sounds like there might be some preference for storing them in `scanner RAS` per the initial commit. Since `iEEGCoordinateUnits` is required, I think this is perfectly reasonable. Maybe this is more consistent with the MRI parts of BIDS? Do you know @sappelhoff?

If that's the case, then I think making a PR to make sure that the units match the values (i.e. if all the `mm` values are between 1 and -1 this raises a warning or if any `m` value is outside 1 or -1) in the validator and then, more importantly, in the BIDS standard templates part of the specification making explicit that the coordinates are to be in `scanner RAS` if shared as a template.

**Comment by oesteban** [comment]
> It looks like all the following templates are in BIDS but not `templateflow`: `ICBM452AirSpace`, `ICBM452Warp5Space`, `IXI549Space` `fsaverageSym`, `MNI152NLin2009bSym`, `NIHPD`, `OASIS30Atropos` and `Talairach`. That's about half of the total templates but there is a nice fetcher so it might be worth adding by PRs. From just checking `UNCInfant` it does look like the `AnatomicalLandmarkCoordinates` I found previously look reasonable. Those might be nice to add as well.

Yes, if those templates are not uploaded it might be for two reasons: (i) we haven't done so because we did not find the time/interest to do it; (ii) the license is incompatible.

So, if you are willing to push templates up, I'll be more than happy to help with support and also actually preparing them for upload. If you want to start now, it would be ideal for TemplateFlow.



> So it sounds like there might be some preference for storing them in `scanner RAS` per the initial commit.

Voxel coordinates are implicit, so long you are storing gridded data (which seems the case for BIDS+NIfTIs). Basically, you have both.

Although it is not common for T1w images, some other sequences may not have the RAS and Voxels axes aligned, so it is very important that the NIfTI files are completely and correctly specified (I'm referring to the x-form headers).

I would imagine that you basically want to store a TSV metadata file with RAS positions of the landmarks, is that correct? (or maybe on the JSON sidecar, I don't remember what the specification says).

@satra thanks for the ping; @sappelhoff thanks for assuming I know about this - not sure I actually know enough about the problem at hand (luckily I know about templateflow :P)

**Comment by alexrockhill** [comment]
Great!

The `AnatomicalLandmarkCoordinates` in the BIDS specification are in a json sidecar for a T1 in voxel coordinates as per the part of the spec I've been following but it's not hard to change them to `scanner RAS`.

I'll have to look up the licenses but all the T1s are gathered in the Google Drive link above (Talairach just has an aseg though and some of them are brainmasked).

**Comment by robertoostenveld** [comment]
Coming a bit late to the party... I have two comments that relate to the staring point:

> Most importantly, what is the coordinate frame of standard template channel locations

EEG and iEEG channels do not have locations, it is electrodes that have locations.  BIDS raw is for storing measured data, not for storing templates. In BIDS derivatives I can imagine spatial normalizations etc having been applied and templates playing a role.

**Comment by alexrockhill** [comment]
> Coming a bit late to the party... I have two comments that relate to the staring point:
> 
> > Most importantly, what is the coordinate frame of standard template channel locations
> 
> EEG and iEEG channels do not have locations, it is electrodes that have locations.  BIDS raw is for storing measured data, not for storing templates. In BIDS derivatives I can imagine spatial normalizations etc having been applied and templates playing a role. 
> 
> 

I agree with your point and understand the distinction between electrodes locations and channels. I think colloquially when you assign an average reference for instance and there is a one-to-one mapping between electrode positions and virtual channel locations, sometimes the distinction gets deemphasized and it's good to make sure by the time the verbiage makes it into the official specification that it is clear.

On the second point, I completely agree and when I wrote the templates part of this tutorial for MNE-BIDS https://mne.tools/mne-bids/dev/auto_examples/convert_ieeg_to_bids.html, I basically begged people to share in ACPC space for the individual subject and not a template space, which I agree is derived. I explained the complexities of the transformation to a template and the copy-of-a-copy problem preventing you from transforming from one template to another. Unfortunately, a lot of people probably will want to share (and a few so far have wanted to share) their data in template space because it's allowable by BIDS. I would be for removing this option but allowing it in derivatives but that's a pretty big change. In my opinion, better now than when the use of templates has really taken off but I think that's a group decision and someone had a reason for adding it in the first place.

**Comment by dorahermes** [comment]
A couple of things here with respect to sharing iEEG electrode positions: 
- ACPC without a nifti is not a good definition, since some neurosurgeons define the zero point in ACPC space as the mid commissural point, others use the anterior commissure. We really need an anatomical scan to interpret individual subject iEEG positions (whether in voxels or millimeters). 
- Some groups are starting to move away from sharing individual subject iEEG electrode positions for de-identification purposes, and only share e.g. MNI152 locations, so there needs to be a way to share iEEG electrode positions in a standard space. Again, this standard space only makes sense wrt an accompanying anatomical scan/definition.
- Some older legacy iEEG datasets only calculated electrode positions in Talairach coordinates, because they only had an x-ray, but no CT/MRI and they simply do not have individual subject space coordinates.

**Comment by alexrockhill** [comment]
To give my take on your points:
> 
> * ACPC without a nifti is not a good definition, since some neurosurgeons define the zero point in ACPC space as the mid commissural point, others use the anterior commissure. We really need an anatomical scan to interpret individual subject iEEG positions (whether in voxels or millimeters).

I agree, my opinion would be to require a T1 for that subject in the BIDS dataset if the coordinate frame is ACPC which I don't think is validated currently.

> * Some groups are starting to move away from sharing individual subject iEEG electrode positions for de-identification purposes, and only share e.g. MNI152 locations, so there needs to be a way to share iEEG electrode positions in a standard space. Again, this standard space only makes sense wrt an accompanying anatomical scan/definition.

I'm not sure I understand how the positions of the electrodes could be used to identify someone. I would guess some groups would have more qualms over sharing the defaced T1 necessary for ACPC definition but the positions of the electrodes in template space vs individual space have very little to do with the patient's identity so I don't think that's a good argument. In my personal opinion, I don't think this should be BIDS-compliant, in this case the raw data isn't being shared. Now whether that's a warning or an invalid dataset might be the point of discussion, but I really don't think this is a good argument for allowing template coordinates for electrodes.

> * Some older legacy iEEG datasets only calculated electrode positions in Talairach coordinates, because they only had an x-ray, but no CT/MRI and they simply do not have individual subject space coordinates.

I think we should have some tools to read these in but maybe not the biggest issue supporting this format of data currently.

**Comment by dorahermes** [comment]
- I agree with you about preferring ACPC positions and a defaced T1. 

- Lab and clinical environments use many ways to reconstruct the electrode positions (note that this is reconstruction: source-->raw, not derivation raw-->derived) and some are better than others. 

- Giving a warning about this issue sounds like a good plan, but saying that electrodes in a standard space are not BIDS compliant may keep entire labs from attempting to organize and share their data in BIDS at all. This would be similar to saying that EEG data with only standard 10/20 labels, but no positions are not BIDS compliant.

**Comment by alexrockhill** [comment]
It sounds like we're in complete agreement with the original issue of the coordinate frame but only almost complete agreement about the larger issue of whether iEEG should allow template coordinate frames.

I think there is a pretty big difference between EEG data in the 10/20 configuration and intracranial data as far as utility seeing as a couple centimeter error in the EEG positions will most likely marginally effect results for EEG but may make the interpretation entirely different for iEEG. I'm really not sure the best solution, but as you can see comparing the symmetric diffeomorphic warp to `fsaverage` (in https://mne.tools/dev/auto_tutorials/clinical/10_ieeg_localize.html) vs the Talairach transform (in https://mne.tools/dev/auto_tutorials/clinical/20_seeg.html), there is a pretty big difference will hinder analysis to some extent. I think a warning is the only way to influence people toward sharing in `ACPC` without pushing people away from BIDS, but I worry that the ease of not having to share individual T1s will make it so that this is very common and really lower the quality of BIDS iEEG data.

**Comment by robertoostenveld** [comment]
I do not object to sharing data in BIDS where part of that data has been imputed on the basis of a template, as long as that is explicitly clarified.

This for me not only applies to electrode positions, but also to other aspects of data. E.g., at the Donders Centre for Cognitive Neuroimaging we could in principle use the modus of our research participants and fill out for each of them that they are 23 year old  males (as we often recruit students as participants for cognitive experiments, and I think we have 55% males and 45% females). However that is not a very accurate description of the real distribution in age and sex. If I were to encounter a dataset where all rows in the `participants.tsv` were to specify male 24y, I would be suspicious. Idem if I encounter an EEG dataset where the reported (template) electrode positions are identical over all participants. However iEEG electrode positions start with (clinical) inter-individual variability, which then might be projected through a researcher or lab specific coregistration pipeline. That pipeline might be systematically different between labs (e.g. because labs using different software), but in the reported iEEG locations I cannot tell the real variability in the electrodes (over subjects) apart any more from the variability that might be due to choices that the researcher made. 

I am fine (and in general very happy!) if raw data gets shared and *also* if the efforts from researchers that process/curate that data are shared, which might involve processing of the individual data using templates. But I would like to be able to recognize the difference between real (raw) data and between the choices that the researcher might have made along the lines. That difference might for example be documented by saying that a specific dataset is "derived", as that requires in the `dataset_description.json` the specification of the processing pipeline. I would also be OK (but less happy than I would have been otherwise) if you would share the same data as if it were "raw", as long as you are able to document (and upon reuse someone else can figure out) what happened to the data.

**Comment by alexrockhill** [comment]
Good points! I am in agreement that it's a bit misleading to allow template positions in the same field that is used for raw data. Perhaps the simplest fix would be to move the template positions into a location for derived data and somehow encourage sharing the steps necessary to derive their locations.
