### ISSUE TITLE
Are tabular files in BIDS allowed to have any blank column names?

### ISSUE THREAD

**Issue by VisLab** [bids-standard/bids-specification#1105]
I have read the spec several times and cannot determine whether this is allowed or not.  (Tabular files are `.tsv` files with a column header as opposed to `timeseries.tsv` type files which do not have column headers.)

If blank column names are allowed, can there be an arbitrary number of them?

**Corollary:**  If column names do not have to be unique, do the JSON sidecar keys apply to equally to all of the duplicates?

**Comment by sappelhoff** [comment]
I just performed a short validator test and it does not warn or raise an error when column headers in TSV files are duplicated.

When column headers are blank, it raises a generic "empty cell" error, rather than a more appropriate "header missing" error:

> [ERR] Empty cell in TSV file detected: The proper way of labeling missing values is "n/a". (code: 23 - TSV_EMPTY_CELL)

I also haven't found any rule in the [spec](https://bids-specification.readthedocs.io/en/latest/02-common-principles.html#tabular-files) whether duplicated headers and/or blank headers are allowed.

According to me, neither should be allowed, so I'd be up for adding a rule like:

> Column headers in TSV files MUST be unique in the file and MUST NOT be empty (blank).
