### ISSUE TITLE
Roadmap for the next release (1.7.1 or 1.8.0?)

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#1118]
I found only reference to 1.7.1 in https://github.com/bids-standard/bids-specification/issues/1088#issuecomment-1125403853 and we are at v1.7.0-329-gd3429fba ATM. Although most of the changes are concerned with further formalization of the `src/schema` (currently `src/schema/SCHEMA_VERSION` is at 0.2.0 and was absent in 1.7.0), I wonder what else should get in before release happens?

**Comment by sappelhoff** [comment]
#918 would be nice, I had this on my plate for a long time now ...

**Comment by sappelhoff** [comment]
Just a note: currently it looks like we will have a 1.8.0 release with NIRS landing in the spec, rather than a 1.7.1 release in between. We will soon schedule the community review for NIRS (which will take 2 weeks) and then we'll schedule a spec freeze and release ... I expect all of this to happen within the next 6-8 weeks or so.

**Comment by sappelhoff** [comment]
Update: In yesterdays maintainers meeting we have discussed to start the community review period for NIRS on 2022-09-01. This period will take 14 days, followed by a 5-business-day long spec-freeze (no PRs should be merged except for critical bug fixes, see [guidelines](https://github.com/bids-standard/bids-specification/blob/master/Release_Guideline.md#guidelines)).

Thus, I expect a 1.8.0 release at the end of September.

The community review period was scheduled so "late", because in the months of July and August many people are on vacation.

Furthermore, we have decided against an interim 1.7.1 release, because in the past we have received complaints about too many released in close succession.

I will migrate items from the [1.7.1](https://github.com/bids-standard/bids-specification/milestone/11) milestone to the [1.8.0](https://github.com/bids-standard/bids-specification/milestone/12) milestone and close the 1.7.1 one.

**Comment by yarikoptic** [comment]
> Furthermore, we have decided against an interim 1.7.1 release, because in the past we have received complaints about too many released in close succession.

hm, interesting.  I would hope that eventually all the patch releases could come out frequently enough and users could be certain that they are just "patches", thus fixing some issues (typos, better wording without change of meaning etc) without affecting any datasets/software which wants to be compliant with BIDS 1.7.x series. (well, ideally it should be all the way for 1.x series, and allow for 1.MINOR to come out with new features)

FTR "in close succession" , I guess was for 1.2.2 to 1.3.0 to 1.4.0 and 1.5.0 to 1.6.0 (2 months)

```shell
$> grep '\[v' src/CHANGES.md 
## [v1.7.0](https://github.com/bids-standard/bids-specification/tree/v1.7.0) (2022-02-15)
## [v1.6.0](https://github.com/bids-standard/bids-specification/tree/v1.6.0) (2021-04-22)
## [v1.5.0](https://github.com/bids-standard/bids-specification/tree/v1.5.0) (2021-02-23)
## [v1.4.1](https://github.com/bids-standard/bids-specification/tree/v1.4.1) (2020-10-13)
## [v1.4.0](https://github.com/bids-standard/bids-specification/tree/v1.4.0) (2020-06-11)
## [v1.3.0](https://github.com/bids-standard/bids-specification/tree/v1.3.0) (2020-04-14)
## [v1.2.2](https://github.com/bids-standard/bids-specification/tree/v1.2.2) (2020-02-12)
## [v1.2.1](https://github.com/bids-standard/bids-specification/tree/v1.2.1) (2019-08-14)
## [v1.2.0](https://github.com/bids-standard/bids-specification/tree/v1.2.0) (2019-03-04)
## [v1.1.2](https://github.com/bids-standard/bids-specification/tree/v1.1.2) (2019-01-10)
```

I on the other hand somewhat dislike huge bundled releases which cram together lots of changes, making it more difficult to grasp everything they bring.  But ok -- it will be 1.8.0 some time in Sep 2022!

**Comment by yarikoptic** [comment]
anyways, question was answered, no need to keep open
