### ISSUE TITLE
Task metadata for PET 

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1188]
There seems to be no mention of the typical metadata usually associated with the task  entity for PET (TaskName, Instructions, TaskDescription...). 

Cannot recall if this was intentional or overlooked?

@melanieganz @mnoergaard

Any idea?

**Comment by melanieganz** [comment]
Uh, good catch. I guess this was overlooked. @mnoergaard  and I will be on fixing it.

**Comment by mnoergaard** [comment]
This was intentional at the time because it would require a long description of a task from the fMRI section of BIDS to be present in the PET BIDS section. Back then, we agreed to keep it out for now because 99% of PET data is rest (i.e. no task), and it seemed slightly confusing to include. But maybe we should consider to add it. It is currently allowed (according to the validator) to include the task entity for PET data.

**Comment by Remi-Gau** [comment]
> This was intentional at the time because it would require a long description of a task from the fMRI section of BIDS to be present in the PET BIDS section. Back then, we agreed to keep it out for now because 99% of PET data is rest (i.e. no task), and it seemed slightly confusing to include. But maybe we should consider to add it. It is currently allowed (according to the validator) to include the task entity for PET data.

ah yes. I now remember we had this discussion. The task being present in so many datatypes leads to an amount of repeats across sections that irks me to no end, so I hear you. Still planning to do some refactoring of this to remove duplications at one point.

I can draft something short and you let me know: I cared more about saying explicitly what metadata could be added.

**Comment by mnoergaard** [comment]
That would be great, @Remi-Gau  - thanks!

**Comment by Remi-Gau** [comment]
Will update PET example too: 

https://github.com/bids-standard/bids-examples/blob/master/pet005/sub-01/ses-intervention/pet/sub-01_ses-intervention_task-eyes_pet.json
