### ISSUE TITLE
New BEP extracted from BEP025 ("MIDS")

### ISSUE THREAD

**Issue by josator2** [bids-standard/bids-specification#1275]
### Your idea

Dear Everyone,

Following the guidelines discussed in this issue:

- https://github.com/bids-standard/bids-website/issues/236

I am proposing to atomise the ideas in BEP025 into separate BEPs for inclusion in BIDS. The first BEPs I would like to draft are one of the fundamental part of BEP025. Add the OPTIONAL use of a label for any image type that is currently stored in bids and can even be applied to future image types. This tag would specify the body part being analysed in the image. It would be exemplified with already proposed BIDS structures and explain why these tags help to organise data and facilitate management in developing AI tools.

**Comment by tsalo** [comment]
Just to clarify, this issue is related to one proposed new entity, like `bodypart-<label>`? If so, I don't think that necessitates an entirely new BEP. We've added entities outside of BEPs in the past. 

From a schema perspective, adding a new entity to indicate the body part is pretty easy. Tooling would be affected, but it would be a lot like `part`, where, if the entity is missing entirely, we assume the data are magnitude values, so most tools need to look for `part-mag` or no `part` at all when selecting files.

The main question, I guess, would be whether this falls within BIDS's scope. To gauge that, this issue will need input from the community, I think. Pinging @bids-standard/maintainers for their thoughts.

**Comment by josator2** [comment]
Regarding this issue, I would prefer to have it in a document to show this concept within BEP025 so that the community can give their opinion inside the document. But I would most like to resolve this issue as soon as possible in order to proceed with other concepts within the BEP and integrate them into BIDS.

**Comment by sappelhoff** [comment]
closed in favor of https://github.com/bids-standard/bids-specification/issues/1569
