### ISSUE TITLE
Clarification of task entity in the appendix 

### ISSUE THREAD

**Issue by melanieganz** [bids-standard/bids-specification#1314]
### Clarification of task entity in appendix

In the current description of [`task-<label>`](../appendices/entities.md#task) it states wrt definition of task: 

task
Full name: Task
Format: task-<label>
Definition: Each task has a unique label that MUST only consist of letters and/or numbers (other characters, including spaces and underscores, are not allowed). Those labels MUST be consistent across subjects and sessions.

@satra commented in [PR 1185](https://github.com/bids-standard/bids-specification/pull/1185) on the last sentence here not being clear, see [here](https://github.com/bids-standard/bids-specification/pull/1185#discussion_r987993984). Specifically, the question was what does this mean if half the subjects do the task and half don't? @Remi-Gau suggested to update this in general, but since it has broader implications, I made this separate issue for it.

Now my understanding is similar to @Remi-Gau's,  meaning label task-foo for subject 1 must mean the same thing as task-foo for subject 2. There is no restrictions of the type "all participants must have done all the tasks." 

So I propose to extend the last sentence to say:
"Those labels MUST be consistent across subjects and sessions, meaning label task-foo for subject X must mean the same thing as task-foo for subject Y."

Opinions or objections?

**Comment by satra** [comment]
> "Those labels MUST be consistent across subjects and sessions, meaning label task-foo for subject X must mean the same thing as task-foo for subject Y."

@melanieganz - thank you. this is better.

**Comment by sappelhoff** [comment]
I agree with this clarification

**Comment by Remi-Gau** [comment]
There other occurrences of this sentence that could be deleted because it appears in the definition.

For task:

https://github.com/bids-standard/bids-specification/blob/7240c43bd66395b8776b07eb3548174ab06aa9d7/src/04-modality-specific-files/09-positron-emission-tomography.md?plain=1#L82

https://github.com/bids-standard/bids-specification/blob/7240c43bd66395b8776b07eb3548174ab06aa9d7/src/04-modality-specific-files/07-behavioral-experiments.md?plain=1#L27

I have found more occurrences of "consistent across subjects and sessions" in the spec for some other labels notably for the `acq` one or the `trc` one.

https://github.com/bids-standard/bids-specification/blob/7240c43bd66395b8776b07eb3548174ab06aa9d7/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md?plain=1#L587

https://github.com/bids-standard/bids-specification/blob/7240c43bd66395b8776b07eb3548174ab06aa9d7/src/04-modality-specific-files/10-microscopy.md?plain=1#L135

https://github.com/bids-standard/bids-specification/blob/7240c43bd66395b8776b07eb3548174ab06aa9d7/src/04-modality-specific-files/09-positron-emission-tomography.md?plain=1#L93

The `acq` label definition also include this sentence: https://bids-specification.readthedocs.io/en/latest/appendices/entities.html#acq

But it does not specify what is meant by "consistent" either.

In general I would not mind if that was actually a spec wide recommendations of what we mean for "consistent" once and we said it applies to all "labels". It would remove a lot of duplication I think. Also because as the spec stands right now, this recommendation does not exist for other labels which opens the door to have things like `sub-01_rec-foo_T1w.nii` and `sub-02_rec-bar_T1w.nii` where `foo` and `bar` actually mean the same thing.

Only exception I can find is for the sample label in microscopy: https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/10-microscopy.html#filename-entities.

> The label MUST be unique per subject and is RECOMMENDED to be unique throughout the dataset.

But this sentence in itself could be an exception to the otherwise spec wide recommendation.

Any thoughts?

FYI: I am fine with a much smaller change, was just trying to see how we can achieve more internally consistency about what we mean by consistent... (Sorry... I had to).

**Comment by satra** [comment]
> achieve more internally consistency about what we mean by consistent

nicely done @Remi-Gau 

a common recommendation with potential overrides sounds good to me. it may be helpful to point to the exception from the common language.

**Comment by Remi-Gau** [comment]
@melanieganz do you want to start this as PR or should I go for it?

**Comment by sappelhoff** [comment]
>>    achieve more internally consistency about what we mean by consistent
>
> nicely done @Remi-Gau
>
> a common recommendation with potential overrides sounds good to me. it may be helpful to point to the exception from the common language.

:100: agreed, thanks a lot for diving just a bit more deeply into this @Remi-Gau!

**Comment by Remi-Gau** [comment]
Will take care of the PR

**Comment by melanieganz** [comment]
This discussion has ended up in a merged [PR](https://github.com/bids-standard/bids-specification/pull/1185). Hence, this issue is closed.
