### ISSUE TITLE
Mapping from google doc version of specification to github directory structure

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bids-specification#133]
Hi - I think this is probably a good question for @franklin-feingold but anyone who knows the answer is welcome to reply!!

I'm looking to match up some of the sections in the released version of the BIDS specification (v1.1.1): (https://bids.neuroimaging.io/bids_spec.pdf) and [the locked google doc](https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit) with the read the docs version this repository builds: https://bids-specification.readthedocs.io/en/stable.

Specifically section 8 (Detailed file descriptions) ([google doc](https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.v9uqdvt04vsf)) seems to have disappeared. I think its now in [04-modality-specific-files](https://github.com/bids-standard/bids-specification/tree/master/src/04-modality-specific-files)?

I had a read of the [src/CHANGES.md](https://github.com/bids-standard/bids-specification/blob/master/src/CHANGES.md) file but I think it's a bit difficult to see where the restructuring happened.

There's also the [TOC.md](https://github.com/bids-standard/bids-specification/blob/master/TOC.md) file but I think that is just a copy from the old google doc? The links don't go anywhere. Might be a good reference for clarifying the mapping though!

Does anyone have a reference to which parts have been mapped to where? 

If it doesn't exist then I can make a new issue to make it clear that it's a task that would welcome a contributor to help with 😄 

---

Update: I think from reading [src/CHANGES.md](https://github.com/bids-standard/bids-specification/blob/master/src/CHANGES.md) that there's actually a released 1.1.2 version....I'm not sure how to read that on readthedocs though 😬

**Comment by sappelhoff** [comment]
reading this made me aware that 

- [https://bids-specification.readthedocs.io/en/stable/](https://bids-specification.readthedocs.io/en/stable/) does not advertise its version on the main landing page, we should probably change this

- [https://bids.neuroimaging.io/bids_spec.pdf](https://bids.neuroimaging.io/bids_spec.pdf) does currently *not* link to the most recent version of the spec, which is as @KirstieJane pointed out 1.1.2 ... I think we should automate this in our release cycles

I cannot be of help to the main issue, sorry @KirstieJane :-)

**Comment by KirstieJane** [comment]
Thanks @sappelhoff - please could you make two new issues for those two tasks? They seem like separable tasks that others could pick up without having to answer my question!

(Let me know if you don't have time and I will 😸)

**Comment by franklin-feingold** [comment]
Hi @KirstieJane, 

The detailed file descriptions has been organized into the [Modality-agnostic files](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html). The relevant PRs that did this reformatting were - https://github.com/bids-standard/bids-specification/pull/13, https://github.com/bids-standard/bids-specification/pull/21, https://github.com/bids-standard/bids-specification/pull/28 ([This PR](https://github.com/bids-standard/bids-specification/pull/28) has the [mapping](https://github.com/bids-standard/bids-specification/pull/28#issuecomment-426747060) you are looking for)

Regarding the pdf version of the specification. On http://bids.neuroimaging.io/, it currently links out to the readthedocs specification for the latest stable release. One can also use the version number (i.e. https://bids-specification.readthedocs.io/en/v.1.1.2/) and it will land you at the same place. Using the version number instead of stable could be added to the [Release Protocol](https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md). It would be sending a PR to the website to update that link.

**Comment by KirstieJane** [comment]
Thanks @franklin-feingold! Sorry I never replied here!

I think the discussion at #150 can supercede the discussion here. The main point for this thread from my point of view is that the change log is very difficult to read. I don't think I could have found that re-mapping without your help!
