### ISSUE TITLE
The readthedocs rendering of the spec should advertise the version

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#134]
[https://bids-specification.readthedocs.io/en/stable/](https://bids-specification.readthedocs.io/en/stable/) does not advertise its version on the main landing page, we should probably change this.

Perhaps display it somewhere in this corner?

![image](https://user-images.githubusercontent.com/9084751/51684546-91c72080-1fec-11e9-98a7-bc7b6dc0d671.png)

**Comment by sappelhoff** [comment]
> Perhaps it could go into the text as a third paragraph indicating the latest stable release? (under the get started paragraph)

yes, that would be an easy to do alternative. But in the corner would be preferable I think, because it can be seen regardless of the sub-page a reader might currently be on.

**Comment by franklin-feingold** [comment]
We are able to edit the corner header by changing the site_name in the [mkdoc.yml](https://github.com/bids-standard/bids-specification/blob/master/mkdocs.yml). However, it is not immediately clear how this permeates across stable and latest releases (I think to both, but further simulations are needed to confirm my suspicion). Regardless though I think latest and stable will be part of the same version because stable takes the latest release and latest is current to master. Master should not be version(s) ahead (i.e. stable at v1.1.2 and master at v1.1.3 without a release).

If we do find there are different versions across necessitating more dynamic version control site_name, It appears this has been discussed over at [mkdocs since 2014](https://github.com/mkdocs/mkdocs/issues/193). There appears to be a solution called [mike](https://pypi.org/project/mike/) that could handle this exact versioning issue.

**Comment by sappelhoff** [comment]
> Regardless though I think latest and stable will be part of the same version because stable takes the latest release and latest is current to master. Master should not be version(s) ahead (i.e. stable at v1.1.2 and master at v1.1.3 without a release).

yes, master should never be a version ahead of the latest release in my opinion. I think of it as:
- stable 1.1.2
- master 1.1.2-dev

i.e., only adding `-dev` to the stable version to indicate that this is the latest version.

would be cool if we could add the `-dev` suffix to the version for the "latest" rendering of readthedocs.

**Comment by franklin-feingold** [comment]
That sounds good to me. I think this all can be integrated and be a part of the Release Protocol. I will start putting together how that would look and submit a PR.

**Comment by sappelhoff** [comment]
@franklin-feingold since #137 has been merged, this issue can be closed - correct? If I understand it correctly, we will have the version advertised when making a new release?

**Comment by franklin-feingold** [comment]
yup! this issue can be closed and yes as we go through the [Release Protocol](https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md) this should have the version at the top for the stable and latest versions of the specification

**Comment by sappelhoff** [comment]
great, thanks again!

**Comment by sappelhoff** [comment]
it's working as expected and looking good :-)

![image](https://user-images.githubusercontent.com/9084751/52695621-4d84cb80-2f6d-11e9-8b5c-c5e0443d8423.png)
