### ISSUE TITLE
iEEG specification for session names

### ISSUE THREAD

**Issue by ftadel** [bids-standard/bids-specification#168]
@choldgraf @dorahermes
In the iEEG specification, it would be useful to include recommendations on how to name the sessions corresponding to different steps of the surgery:
- pre-implantation: ses-pre, ses-preimp?
- post-implantation: ses-post, ses-postimp?
- post-surgery (after removing the implanted electrodes and performing the surgery): ses-post, ses-postop?

This would help avoiding amguities (eg. what would "ses-post" mean) and building automated procedures (computing resection volumes, detecting electrodes in post-implantation CT, etc)

**Comment by choldgraf** [comment]
Good point!

I'm +1 on adding recommended practices here, though probably not something we want to strictly enforce with the validator

**Comment by chrisfilo** [comment]
Why not instead of having weak recommendations for session names that cannot be reliably interpreted by machines define a new column with a controlled vocabulary of allowed values to `_sessions.tsv`?

**Comment by dorahermes** [comment]
I would be +1 on having a well-defined description for clinical labels. I am currently working with similar problems and also collaborate with Matteo Demuru (@suforraxi) who studies ECoG recordings during surgery.

Some quick thoughts on the use cases: 
1) The typical use case is 1 surgery, some scans before (preimplant) some scans with electrodes in place (withimplant), some scans after (potentially including resection) without electrodes in place (postimplant).
2) Labels pre/post would be too general to recommend because they can be pre/post anything. 
3) However, there can sometimes be several pre sessions: preimplant1, preimplant2?
4) There can sometimes be several surgeries, where electrodes are added in a second surgery or where a patient comes back several years later for a second surgery, pre/post which surgery?

**Comment by ftadel** [comment]
Additional question:
It is mentioned multiple times in the iEEG specs that we can place the electrodes using a CT scan, but there is currently no way to have a CT scan in a BIDS dataset... is there?

**Comment by dorahermes** [comment]
Since there is a BEP for CT (BEP024), the location for the CT is currently not specified in the iEEG-BIDS extension. 
(As a pragmatic solution, I am currently placing the CT in sourcedata)

**Comment by ftadel** [comment]
Has anybody decided on formal clinical labels for the sessions yet?

**Comment by dorahermes** [comment]
No formal labels have been established for sessions yet and my current impression is that this is very study/site specific. The sessions.tsv gives the ability to annotate time-lines. Happy to have a look if anyone has some suggestions.

**Comment by ftadel** [comment]
Thanks for the update.
I was fixing a few things on the iEEG BIDS-examples, so I was checking everything was up-to-date.

If we consider this is site-specific and that the specs should not give any additional recommendations, then this issue doesn't need to move forward. Should we close it?

**Comment by adam2392** [comment]
I've found `ses-presurgery<num>` and `ses-postsurgery<num>` to be adequate for my uses. Multiple scans before/after implantation can be distinguished using `acq` and `run` entity. 

Since iEEG electrodes stay the same within session, then most of the times there is just the need for `ses-presurgery` and `ses-postsurgery`, where there might be different electrodes. Multiple implantations can be then defined using the `<num>`. 

Since iEEG can't be recorded "preimplantation", I just stick any relevant scans (e.g. MRI) into the `ses-presurgery` with other entities to distinguish preimplantation vs postimplantation.

**Comment by dorahermes** [comment]
I think it is ok to close this as an issue. 

@franklin-feingold I am not sure where recommendations/helpful conversations are currently stored anywhere?

**Comment by franklin-feingold** [comment]
me too - perhaps in the starter kit? that seems like a good place - wdyt?

**Comment by dorahermes** [comment]
Starter kit would be useful as long as it is clear that it is a recommendation. Feel free to update the wiki! Can you perhaps include a link to an example set?

**Comment by ftadel** [comment]
> I've found ses-presurgery<num> and ses-postsurgery<num> to be adequate for my uses. 

Distinguishing two standard post-surgical stages is often relevant: 
- post-implantation = after the SEEG/ECOG implantation surgery
- post-operatory / post-surgery / post-resection = after the surgical treatment / after the removal of the SEEG/ECOG implants

Hence two sets of suggestions for the ses- or acq- labels:
- pre/post/postop
- preimp/postimp/postop

**Comment by ftadel** [comment]
> Can you perhaps include a link to an example set?

https://github.com/bids-standard/bids-examples/tree/master/ieeg_epilepsy_ecog/sub-ecog01

> I think it is ok to close this as an issue.

Closing it now then.
It would be great if someone could reference this discussion somewhere, as it will probably come up again some day.
Thanks!
