### ISSUE TITLE
[BUG] Entity requirements for MPM suffix do not appear correct

### ISSUE THREAD

**Issue by lbanellis** [bids-standard/bids-specification#1683]
### Describe your problem in detail.

page in the spec https://bids-specification.readthedocs.io/en/stable/appendices/file-collections.html
we tested with @melanieganz @CPernet @Remi-Gau MPM it is valid only if entities flip and mt are present 
- issue 1: in the table it does not explain what are the required entities
- issue 2: in our case we use multiple echo times and single flip, makes no sense one entity over others matter more 

### BIDS specification section

https://bids-specification.readthedocs.io/en/latest/...

**Comment by lbanellis** [comment]
issue one can be fix right now, then we can disccuss issue 2 how to solve it
@agahkarakuzu

**Comment by Remi-Gau** [comment]
Relevant schema section: 

https://github.com/bids-standard/bids-specification/blob/3bf993b1d5d40e87375f554f0214d321e9696677/src/schema/rules/files/raw/anat.yaml#L176-L198

**Comment by agahkarakuzu** [comment]
@lbanellis the [entity table](https://bids-specification.readthedocs.io/en/stable/appendices/entity-table.html#magnetic-resonance-imaging) explains required entities. As well as the suffix:
<img width="742" alt="image" src="https://github.com/bids-standard/bids-specification/assets/9632322/c05b040e-866e-431f-85b4-df59164b3d02">

> issue 2: in our case we use multiple echo times and single flip, makes no sense one entity over others matter more

It makes sense in the context of an `MPM` acquisition, which is why it exists as a file collection. For example, if you are not varying your FAs, how do you get an R1 map? If you are not, is that an MPM?

**Comment by CPernet** [comment]
@agahkarakuzu what we meant is it makes no sense the echo is not mandatory and flip is, given that here the parameters that matters is echo time, ie what is mandatory or optional is weird

**Comment by CPernet** [comment]
issue one is to have the info in the table

**Comment by lbanellis** [comment]
Also, noticed the BIDS validator is very sensitive to the order of the entities (is only happy when echo and run is after acq)

**Comment by Remi-Gau** [comment]
> Also, noticed the BIDS validator is very sensitive to the order of the entities (is only happy when echo and run is after acq)

That's expected: entities can only appear in a specific order. 

The order when taking ALL entities into account is the one you can see in this document:
https://bids-specification.readthedocs.io/en/latest/appendices/entities.html

More succintly put in the schema:
https://github.com/bids-standard/bids-specification/blob/3bf993b1d5d40e87375f554f0214d321e9696677/src/schema/rules/entities.yaml

**Comment by lbanellis** [comment]
Thank you for your replies, this issue was written with the organisers of the BIDS BrainHack event as it took us some time to convert the MPMs to validated BIDS with the organisers help.

**Comment by Remi-Gau** [comment]
@lbanellis 

Was pointed out to me that sending links to yml files is not the most user friendly. Sorry about that.

The way you usually know how to name files is to check the filename templates that are generated for each datatype.

The one with MPM should be right there:

https://bids-specification.readthedocs.io/en/latest/appendices/file-collections.html#magnetic-resonance-imaging

![image](https://github.com/bids-standard/bids-specification/assets/6961185/bda5a7fc-0027-46ed-be77-6df1437e1696)

This will tell you for a given suffix what are the entities you can use, which ones are required (see the legend dropdown below the templates for more info on that) and in which order they should appear.

All filenames templates of all datatypes are also listed in a single page on the bids starter kit

https://bids-standard.github.io/bids-starter-kit/folders_and_files/files.html#anat-anatomical-mri

**Comment by CPernet** [comment]
done a PR just to move info in the main spec -- but I still think it makes no sense for MPM which entities are mandatory vs optional 
- case 1, one acquires data using variable flip angles and on store the various flips but not the inversion time (in the json a single value, makes sense) 
- case 2, one acquires data using multiple inversion times and have the inversion time becomes inherently needed (while optional) to distinguish files and have to store the same flip many times (while being a single value, makes no sense)

**Comment by tsalo** [comment]
@CPernet the definition for "MPM" that we have in the specification is consistent with the entity requirements in the schema. If there is a canonical definition for the MPM protocol that makes it clear what the requirements are, then can you link to that and we can update the definition?

**Comment by CPernet** [comment]
the entity requirement are 'correct' code wise, I am arguing here for reference that scientifically speaking this makes little sense to stores the various flips (mandatory) while the inversion time (optional) if using multiple flip angles data acquisition scheme (which is fine) but have to use the optional inversion time and store the same flip value many times when using a multiple inversion data acquisition scheme (ie either both mandatory or have some conditional if multiple flip, inversion is optional because always the same, if multiple inversion, flip is optional because always the same)
