### ISSUE TITLE
aslcontext.tsv dummy volumes

### ISSUE THREAD

**Issue by nmrotstein** [bids-standard/bids-specification#1762]
Hi,
I have an ASL dataset that I am hoping to convert to BIDS format (to eventually use with ASLPrep), but the sequence that our group is using is structured as an M0 volume, a dummy volume, and then 9 label-control pairs, and the current BIDS specification for the aslcontext.tsv file does not seem to have any option for indicating a dummy volume, just label/control/m0. Could an option for labeling dummy volumes (or an "other" or "ignore" option) potentially be added to the specification for aslcontext.tsv so that it is possible to convert this type of ASL sequence to valid BIDS format?
Thank you!

**Comment by tsalo** [comment]
I don't really understand what a "dummy volume" is in this context, or why dummy volumes are included in the protocol, but this was also brought up by `lucia_sanchez_aranda` on NeuroStars (https://neurostars.org/t/plds-calibration-image-and-dummy-volumes-in-aslprep/26373), so it seems like multiple people are struggling with this.

**Comment by tsalo** [comment]
This has come up once again (https://neurostars.org/t/aslprep-cannot-calculate-deltam/29969), so I'd like to get some resolution on it. What is a "dummy volume" in an ASL scan? What is its purpose? Why put it after the M0 scan and before the control-label pairs? What kind of contrast does it have?

**Comment by effigies** [comment]
@HenkMutsaerts @patsycle Do you have any insight here? It would be trivial to add a `dummy` or similar value to `volume_type`, but I don't know enough to say whether that's appropriate or whether there's another way to achieve what these posters want to achieve.

**Comment by nmrotstein** [comment]
Hi all, I don’t have a direct answer to these questions, but wanted to add
that I’ve been able to successfully run analyses on this dataset in BASIL
with just the m0 and control by just cutting the dummy volume out entirely.
So at the very least, it doesn’t appear to be a critical piece of data.
Adding a new option to volume_type that ASLprep could be told to ignore
(though that’s probably a separate topic for the ASLprep team) might be the
best bet here, unless someone more knowledgeable feels otherwise.

Disclaimer: take all of the above with a grain of salt, I am far from an
ASL sequence expert, so I may be wrong, though someone with more expertise
who I met with recently seemed to also have no issue with the “just remove
it” approach.

**Comment by effigies** [comment]
I don't doubt that you can remove it; I just don't know if there's a better label to apply to such volumes. Today's dummy volume might be tomorrow's diagnostic volume, and annotating data with a description instead of an instruction can allow tools to evolve their behavior without modifying the dataset.

**Comment by aptinis** [comment]
Hi everyone, just wanted to add that I have also encountered this issue in the past. The HCP-A/Siemens 2D MB PCASL sequence consists of 43 label/control pairs (the first 86 volumes), followed by 2 noise images and 2 m0 images for a total of 90 volumes as described [here](https://groups.google.com/a/humanconnectome.org/g/hcp-users/c/2li3DdK5asc/m/unTp5AjhAQAJ).

I am just speculating because this isn't my area of expertise but I think these noise volumes allow for full relaxation between the label/control volumes and the m0 volumes? Maybe it's related to the fact that the m0 TR can be very long compared to the TR for the rest of the volumes? I know for the 2D MB PCASL sequence the m0 TR is 8s vs. 3.58s for the rest of the acquisition. The noise volumes don't have a contrast, they are just background values (there is no brain in the image).

These noise volumes are not used during preprocessing or the estimation of CBF/other measures. They have no value but it would be convenient to have a `discard`, `noise` or `dummy` `volume_type` option in the `*_aslcontext.tsv` instead of having to separately remove these volumes from the NIfTI during BIDS conversion. For example:

```tsv
volume_type
label
control
label
control
...
label
control
discard
discard
m0scan
m0scan
```

**Comment by effigies** [comment]
I do think `noise` could be a good label, if that's what people think they're capturing. Or `noRF`, to match the NORDIC suffix?

**Comment by hgrotzin** [comment]
Hi all, I just wanted to chime in because I'm also having this problem with the current dataset I'm analyzing. We're using a sequence programmed by a team at USC and this is the order of dicoms:
<html>
<body>

Volume # | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16

Volume Type | M0 | Ctl | Tag | Ctl | Tag | Ctl | Tag | Ctl | Tag | Ctl | Tag | Ctl | Tag | Ctl | Tag | Ctl

<br class="Apple-interchange-newline">
</body>
</html>
The first control image (dicom 2) is our "dummy scan" and is not part of any of the tag/control pairs. I second what @aptinis said - it would be great to have an option in the tsv file to remove this volume. Thanks!

**Comment by tsalo** [comment]
@hgrotzin shared her DICOMs with me and I checked the dummy scan. Unfortunately, it looks somewhat like a control volume, rather than a noRF, which I would expect to look like the following:

![image](https://github.com/user-attachments/assets/7ff3fad2-d859-4ed1-b05c-ba7465b949df)

**Comment by effigies** [comment]
So is there a reason not to just call these control volumes and let software decide whether they are useful? Or is the software kind of dumb, and users need to encode a bit more intent?

@mharms I realize you're the one who posted the message linked in https://github.com/bids-standard/bids-specification/issues/1762#issuecomment-2237632417. What do you think about calling these additional volumes "control" or "noise"? Or anything else spring to mind?

**Comment by nmrotstein** [comment]
Yes, it is a software is dumb situation; I actually didn’t know it wasn’t a control volume at first because they look so similar, so I had it coded as control and then spent weeks trying to figure out why my BASIL output looked so weird before reaching out to the sequence developer and being told there was a dummy volume. Leaving a dummy volume coded as control will allow the pipeline to run but messes up the label control subtractions enough to ruin the whole image, so it is super critical that they do not get coded as control. See below for what happens when you label dummy as control vs. when it is correctly excluded from analysis. My personal vote, in the interest of user-friendliness, would be to just code it as "dummy", because that is what people using these sequences will be told that the volume is, but I'd also be fine with @aptinis "discard" proposal.

<img width="403" alt="CorrectlyRemovedDummy" src="https://github.com/user-attachments/assets/e5ac5e18-77c5-4aab-905c-cf268dc664a9">
<img width="406" alt="DummyMisnamedControl" src="https://github.com/user-attachments/assets/ffb7ae9a-27df-4ade-8ecf-b2cdacecbaa1">

P.S. @hgrotzin unless there's two ASL development teams at USC, I'm guessing that you're using a Danny Wang sequence like I am? If so, it looks we have a slightly different sequence but I want to flag that yours might also have some other issues to be aware of other than the dummy scans - namely, that there are a couple parameters where info in the sequence PDF is outright false / has misleading artifacts from a base sequence, which can result in the wrong parameters being set for asl analyses. Happy to take a look at the sequence you're using to confirm, feel free to email me - NRotstein@mednet.ucla.edu

**Comment by aptinis** [comment]
In my case I think they look like noise images and are not just a control image so `noise` would be more appropriate. I am not familiar with NORDIC but maybe `noRF` could also apply? Here's an example of one of the noise volumes (axial view).

<img width="447" alt="Screen Shot 2024-07-31 at 2 09 10 PM" src="https://github.com/user-attachments/assets/2cbe2f2a-3813-4310-9339-b12f6fc7f566">

Maybe we could use `discard` or `ignore` to be more broad to accommodate both use cases? I think it would be good to allow users to encode intent for software given the unique use of the `*_aslcontext.tsv` file for asl. Creating a new volume type would be helpful so that I don't have to remove volumes during BIDS formatting in order to be BIDS valid (since I can't label it a `control` volume).

**Comment by tsalo** [comment]
lol it looks like we have multiple image types that were being conflated here.

@nmrotstein @hgrotzin your images look like control volumes. The question then becomes, what is the purpose of these control volumes? If they're just an extra control volume, then that's fine. I think it's totally reasonable to have an unequal number of control and label volumes, and I can modify ASLPrep to account for this, but is there going to be a problem if CBF is calculated using that first "control" image (which might also be a "noise" image)? If so, then I need to know why and BIDS should include a different `volume_type` value for these volumes. Otherwise, it's just an issue on ASLPrep's end.

@aptinis, your image looks like a noRF volume to me. I'd love to know for sure that the volumes were acquired without an excitation pulse before we commit to the label "noRF", but that's promising.

**Comment by nmrotstein** [comment]
@tsalo For the kind that me and @hgrotzin have, they are _not_ actually control volumes and cannot be treated as control volumes, they just have a deceptively similar appearance. Not sure if you saw the message I sent or if it got buried by the one @aptinis sent at the same time, but basically, if you treat the dummy volume as a control image in CBF calculation, it ruins the entire output image.

I have no idea why the dummy volume breaks things when included (beyond "it is not a control or label image so the subtraction gets messed up), or why it's included at all. But it does need a different BIDS volume type in my opinion to avoid being misclassified/misused by the pipeline.

**Comment by aptinis** [comment]
Our site uses the 2D MB PCASL sequence on a Siemens Prisma scanner. I think we are using the exact same sequence as HCP Ageging. I am not sure how to verify the 2 noise volumes were acquired without an excitation pulse. Is there a DICOM tag I can check? The sequence info can be found [here](https://www.cmrr.umn.edu/downloads/pcasl/) and may give some insight. Or maybe someone from HCP knows?


I agree we're conflating multiple image types here but one of the potential solutions (having a `dummy`, `discard` or `ignore` volume type) could solve both use cases.

Potential solutions
1. For sequences with a dummy volume that is actually a control image allow aslprep to handle it (see potential complexities below)
2. For sequences with a dummy volume that is actually a noise image allow the asl volume type to be `noRF` so that data can be BIDS valid without having to extract noise volumes (aslprep will still need to discard/ignore these noise volumes)
3. Create a dummy or discard volume type for the asl context tsv

Regardless of whether the `dummy` volumes are control or noise volumes they seem to always be between the m0 volume and the "good" control/label pairs to use. I am under the impression that the `dummy` volumes should be discarded and should not be used to calculate CBF even if they are just a "control" image. If they are `noise` volumes (such as in my case) then they definitely shouldn't and can't be used to calculate CBF. I am not familiar with the MR physics of it (maybe we can get an explanation from someone who is) but I speculated above if these dummy volumes allow for full relaxation between the label/control volumes and the m0 volumes? Maybe they are related the vastly different TRs you can have beween the m0 volume and the other volumes (TR 8s vs. 3.58s) or the use of background/prep pulses? It sounds like even if they are just control images @nmrotstein @hgrotzin are being advised to discard those particular volumes.

If aslprep becomes responsible for handling these `dummy` control volumes then I think we have to be very careful about which label/control volumes are used. There are 2 theoretical things to consider
1. there can be multiple discard volumes
2. they are not always in the same place within the 4D NIfTI
For example when the m0 is acquired at the end of the acquisition instead of the beginning
- `control`, `label`, `control`, `label` .... `dummy`, `dummy`, `m0`
- `m0`, `dummy`, `control`, `label`, `control`, `label` ...

The above complexities combined with the unique use of a context tsv file for asl scans may make easier to just allow the user to encode this intent instead of having aslprep handle it. In that case we could just allow a `discard`, `dummy` or `ignore` volume type in the asl context tsv.

**Comment by mharms** [comment]
> So is there a reason not to just call these control volumes and let software decide whether they are useful? Or is the software kind of dumb, and users need to encode a bit more intent?
> 
> @mharms I realize you're the one who posted the message linked in [#1762 (comment)](https://github.com/bids-standard/bids-specification/issues/1762#issuecomment-2237632417). What do you think about calling these additional volumes "control" or "noise"? Or anything else spring to mind?

Sorry, what comment from me are you referring to?  I don't see any comment by me in this particular thread.

**Comment by tsalo** [comment]
@mharms, @effigies was referring to the thread from the HCP Google Group (https://groups.google.com/a/humanconnectome.org/g/hcp-users/c/2li3DdK5asc/m/unTp5AjhAQAJ) that was linked to in the comment in this thread.

**Comment by mharms** [comment]
I found this sentence on p. 171 in http://www.ncbi.nlm.nih.gov/pubmed/25462690:

> Additional EPI images could be optionally collected after the pCASL series with all RF pulses turned off for estimating thermal noise and calculating g-factormaps.

So, either `noise` or `noRF` would seemingly be fine as labels for those volumes.

FWIW, in that paper, they collected 200 noise volumes, so I'm not sure what you can do robustly with two.  I've asked Xiufeng to comment on this thread.

**Comment by tsalo** [comment]
Thanks @mharms. I will open a PR to support `noRF` in aslcontext files. We can also support separate noRF files, the same way we do for BOLD scans.

@nmrotstein @hgrotzin- @effigies proposed allowing "n/a" as a value, since that is an allowed value for missing/unknown values in TSV files within BIDS. I think that would be a great placeholder for now, but I still want to find out what the actual images mean from someone who has a solid handle on the sequence (e.g., Danny Wang).

**Comment by tsalo** [comment]
I bundled the `n/a` option into my PR (#1884), so if anyone who's interested in that PR could take a look at my proposed changes, that would be much appreciated.

> FWIW, in that paper, they collected 200 noise volumes, so I'm not sure what you can do robustly with two. I've asked Xiufeng to comment on this thread.

@mharms I haven't used NORDIC with ASL before, but in my experience people typically acquire only ~3 noRF volumes for BOLD scans, and the folks who use NORDIC the most seem okay with that, so maybe 2 are sufficient for ASL.

**Comment by nmrotstein** [comment]
Thanks @tsalo ! This should work for now; will this PR being merged reflect
in the BIDS validator? If not, is there some other way for us to test that
it works for our data once merged?

@hgrotzin or I can reach out to Danny regarding the purpose of these
volumes (we’ve been discussing the sequence in a separate thread), and will
let you know if/when we hear back.

**Comment by tsalo** [comment]
You _should_ actually be able to replace dummy volumes in the aslcontext file with `n/a` now. It should work without the new PR, since n/a is an allowed value for TSV files already. I might need to make changes on ASLPrep's end, but we can follow up on that in an ASLPrep issue if necessary.

I look forward to hearing how Danny Wang describes these volumes.
