### ISSUE TITLE
Handling BIDS URI in IntendedFor metadata

### ISSUE THREAD

**Issue by dlevitas** [bids-standard/bids-specification#1894]
This question pertains to how BIDS converters should handle BIDS URIs in the `IntendedFor` metadata.

I have not followed the discussions surrounding BIDS URIs; however, the most recent BIDS specification (1.9.0) pushes the concept of using them for fields such as `IntendedFor`:
```
{
   "IntendedFor": [
        "bids::sub-01/ses-pre/func/sub-01_ses-pre_task-motor_run-1_bold.nii.gz",
        "bids::sub-01/ses-pre/func/sub-01_ses-pre_task-motor_run-2_bold.nii.gz"
    ]
}
```

My understanding is that BIDS apps such as fMRIPrep have not (or only recently) supported BIDS URIs, meaning that researchers using older versions of fMRIPrep will presumably encounter errors during SDC if they use the stated format above. Given that BIDS converters are agnostic with regards to which BIDS app versions users employ, it's unclear to me how maintainers of BIDS converters should proceed. Will there will backward compatibility for BIDS URIs, or should users be recommended to use newer versions of tools that support this format?

**Comment by effigies** [comment]
Tools need to support pre-BIDS-URIs if they support BIDS 1.x, so that is a safe conversion target. That said, if I were maintaining a converter, I would probably build in opt-in BIDS-URI functionality now, to help make users aware of them and able to determine whether the tools they use support it.

Possibly we need something like MDN has for API features and note versions where apps started supporting a BIDS feature (either producing or consuming). This would help users and developers make decisions about when to transition their own data / tools.

> should users be recommended to use newer versions of tools that support this format?

As a rule, I think users should use newer versions of tools unless they have a good reason not to. In that case, their processes should basically be frozen at known good sets of versions/configurations of converters and processing tools.

**Comment by dlevitas** [comment]
> I would probably build in opt-in BIDS-URI functionality now

This sounds appropriate.

To clarify, fMRIPrep versions >= 24.x is where support BIDS URIs was included?
