### ISSUE TITLE
[EEG] Some questions about BIDS

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-specification#194]
Dear all, 

during my attempts to bidsify some eeg data, I stumbled on some points that are not clear for me. Could you please clarify them for me?

1. Should the labels of session, acquisition and run be consistent between subjects? 
   - I couldn't find this in the specification, but validator suggests that each subject should have exactly the same set of sessions and acquisitions.
2. Are the fields in events.tsv can be picked only from given table, or I can define my own (with corresponding entry into json)?
   - In doc it says "The tabular files consists of one row per event and a set of REQUIRED and OPTIONAL columns". This suggests that I can choose only from the given fields, but if it's fixed I still need to define labels in json. If other labels are allowed, can you mention it in document?
3. Can you clarify the policy of anonymization? 
   - In description of scans.tsv you require the shift of dates by a fixed amount of days. This implies that the scan date must be also removed from the data file, but   I didn't found it mentioned explicitly. Moreover, EDF format requires an entry of a date -- should it be the same date as in scans.tsv, or I can choose a fixed fake one?

Thanks in advance

**Comment by sappelhoff** [comment]
Not an exhaustive answer, but a start:

Answer to q1
--------------
Can you clarify your question with the use case that you are working on?

I just answer in how far I understand your question for now. "You should be consistent with your labels". I.e., you have two participants in your study, participant 1 had two sessions, and participant 2 had only one session (e.g., because they were sick that day, or the budget was empty, ...)

Then it'd be sensible to call the session labels
- `sub-1_ses-1` and `sub-1_ses-2` for participant 1 ... and
- `sub-2_ses-1` for participant 2

so the labels are consistent, but it is not required that they are equal (because that's sometimes just not the case)

and not
Answer to q2
--------------
You can define your own columns if they are documented in an accompanying JSON file. See the [spec](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/05-task-events.html):

> An arbitrary number of additional columns can be added. Those allow describing other properties of events 

this is documented slightly below the phrase that you quote. But if you think the documentation should be improved with a slight twist of wording, feel free to send a PR!

**Comment by nbeliy** [comment]
Thanks for the answer.

### q1

>so the labels are consistent, but it is not required that they are equal (because that's sometimes just not the case)

That was how I understood the standard. However if some subjects had different sessions labels, validator complained. Before update it complained only about sessions, but now he requires full file names be identical. 
```
 1: [WARN] Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing. (code: 38 - INCONSISTENT_SUBJECTS)
		./sub-COF008/eeg/sub-COF008_task-BL_acq-T2144_channels.tsv
			Evidence: Subject: sub-COF008; Missing file: sub-COF008_task-BL_acq-T2144_channels.tsv
...
		... and 1260 more files having this issue (Use --verbose to see them all).
````
We use (temporarily) the time for acquisition label. So these labels are never the same. 
If labels are allowed to be different, why validator produces a warning?

**Comment by chrisfilo** [comment]
Using time of acquisition as as the value of acquisition is not following it's intended use. It is suppose to distinguish different types of acquisition (for example if you have two MR images with different resolutions). The acquisition time is suppose to go into scans file (see https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#scans-file).

**Comment by sappelhoff** [comment]
q1
---
you might have misunderstood the `acq` label, which is an easy thing to do. We are trying to clarify it with @robertoostenveld in #173 and this [google doc](https://docs.google.com/spreadsheets/d/1pYr8nigiJ6wm8cGaLjj2TsY-or8ELGcjAUXZifktd_4/edit#gid=0)

Please specifically look at this [comment](https://docs.google.com/spreadsheets/d/1pYr8nigiJ6wm8cGaLjj2TsY-or8ELGcjAUXZifktd_4/edit?disco=AAAACpl1YT8) --> I suggest that for now you drop the `acq` parameter

On a different note: The general problem you are pointing out persists ... but that's an issue for the [bids-validator](https://github.com/bids-standard/bids-validator), not the specification. So overall you reported two issues in one go, yay! :-)

q3
---
I'll leave this one open for now, because I'd have to read about it myself ... hopefully somebody else can answer this in the meantime

**Comment by nbeliy** [comment]
##q1

I'm sorry to come back to this acquisition again and again, I'm responsible for bidsifying in laboratory, so I try eliminate any double interpretation and still keep it convenient for us. Moreover, the conversion is intended to happen in automatic workflow, without manual labeling of samples.

>Using time of acquisition as as the value of acq is not following it's intended use. It is suppose to distinguish different types of acquisition

I'm aware of it, and it will be changed for sure. In our case sometimes we have 2 eeg similar scans for same subject and acquisition label is a natural way to distinguish them. The time was used to this goal before the bids era -- so we just kept same labeling.

> We are trying to clarify it with @robertoostenveld in #173 and this google doc

In my naive interpretation, an acquisition is one full session of acquisition data (i.e. one eeg file). If experiment expect only one acquisition per task, then there are no label, and if there a possibility to have several per task, then acq label becomes mandatory.

And then, if one acquisition (one file) can be split into segments, these becomes runs. It fits nicely "uninterrupted repetition of data acquisition".

Please tell me if it is a reasonable interpretation.

**Comment by sappelhoff** [comment]
Sorry for getting back to you so late @nbeliy. I'll try to make up for it with an exhaustive answer.

Have you taken a look at the [definitions](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#definitions) part of the specification?

> **Data acquisition** - a continuous uninterrupted block of time during which a brain scanning instrument was acquiring data according to particular scanning sequence/protocol.

> **Run** - an uninterrupted repetition of data acquisition that has the same acquisition parameters and task (however events can change from run to run due to different subject response or randomized nature of the stimuli). Run is a synonym of a data acquisition.

Given these definitions, your naive interpretation of a data acquisition is correct: One full uninterrupted data recording. Note however, that data acquisition in this sense is DISTINCT from the `acq` parameter (I'll come to that below).

Your second comment that splitting one acquisition into segments would mean having several runs is a bit misguided as far as I can see. With our definitions, data acquisitions and runs are synonymous ... you can say: This data is from acquisition 1 ... or this data is from run 1 (it means the same).

Dividing a data recording into segments AFTER the acquisition sounds like a derivative to me, which is not yet completely defined - please see [BEP021](https://docs.google.com/document/d/1PmcVs7vg7Th-cGC-UrX8rAhKUHIzOI-uIOh69_mvdlw/edit?disco=AAAACoSruhQ&usp_dm=false&ts=5c811e55)

Now having that sorted out, let's come back to the `acq` parameter.

This is defined [here (scroll down a bit)](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data):

> The OPTIONAL acq-<label> key/value pair corresponds to a custom label the user MAY use to distinguish a different set of parameters used for acquiring the same modality. For example this should be used when a study includes two T1w images - one full brain low resolution and and one restricted field of view but high resolution.

With regards to an EEG recording, the `acq` parameter makes little (or none at all) sense, because unlike with a T1w MRI scan, we are not measuring a "stable configuration" (e.g., distribution of white and grey matter in the brain) but a "dynamic process" (e.g., postsynaptic potentials). And we can never re-measure that past dynamic process with a different set of acquisition parameters.

Example (I know you are working with sleep data, so let me try):

- measure EEG in first hour after going to bed on the 4th of May 2018 using `acq-1000fs` (the label could mean sampling rate 1000 for the EEG)

- Now try do do a `acq-250fs` --> it's impossible, because time has passed and the EEG activity of the first hour after going to bed on the 4th of May 2018 will never return


The `acq` parameter CAN be meaningfully used in EEG.

Example:

- You are using the Nasion, Left, and Right Periaruicular Points as reference points for electrode locations (NAS, LPA, RPA)
- To communicate the exact position of NAS, LPA, and RPA, you make photos of the participant (see [here](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#landmark-photos-_photojpg) for an example)
- The photo showing the Nasion could be called `sub-0001_ses-001_acq-NAS_photo.jpg`
- The photo of the Right Periauricular Point could be called `sub-0001_ses-001_acq-RPA_photo.jpg`

... strictly speaking these are not different acquisition parameters (i.e., the settings of the camera are probably the same) - but it would be a valid "re-use" of the acq parameter.

**Comment by sappelhoff** [comment]
And as a bonus, here is my opinion for your

# Q3

I interpret it as such:

> In description of scans.tsv you require the shift of dates by a fixed amount of days. 

yes, for more detail, see [here](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#scans-file)

> This implies that the scan date must be also removed from the data file, but I didn't found it mentioned explicitly. 

yes, the date must be removed or adjusted (see below) in the raw data file. Otherwise this is not a complete anonymization

> Moreover, EDF format requires an entry of a date -- should it be the same date as in scans.tsv, or I can choose a fixed fake one?

I would strongly recommend to use the same date as in scans.tsv

**Comment by sappelhoff** [comment]
closing as solved
