### ISSUE TITLE
[Infra] Add dates to releases in Spec

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#199]
Looking at our changelog, some releases have an associated date, while others do not: https://bids-specification.readthedocs.io/en/stable/CHANGES.html

I think that having the release date next to the version number is helpful because it provides information on how old the latest release is. (and based on that heuristics like "how active is the release cycle/development", "how mature is this release", "is this a new release with potentially a few bugs", ...)

I vote for including this in our release protocol.

**Comment by franklin-feingold** [comment]
Our recent releases (after the github merge) are dated. We get that for free from the [changelog generator](https://github.com/github-changelog-generator/github-changelog-generator). The most recent entry can have a date upon release. The [latest](https://bids-specification.readthedocs.io/en/latest/CHANGES.html) has the changelog dated (after merge)

Adding this would be little weight on current release procedure. The difficulty is once a release is ready to deploy, it would be having to quickly commit on the PR to label that date.

**Comment by sappelhoff** [comment]
> The most recent entry can have a date upon release. The latest has the changelog dated (after merge)

Ahh, I see: [latest](https://bids-specification.readthedocs.io/en/latest/CHANGES.html) does behave like I would expect. The development version does not have a date, but all others do (since moving to GitHub).

 It's just a bit confusing that in the [stable](https://bids-specification.readthedocs.io/en/stable/CHANGES.html) version, the date is not written for the most recent release. I.e., it will probably be written for our currently most recent v1.2.0 as soon as we make a new release, right? Do you know why this is the case?

> Adding this would be little weight on current release procedure. The difficulty is once a release is ready to deploy, it would be having to quickly commit on the PR to label that date.

Can you clarify what you mean by that? Is this a solution for writing the date of the most recent release even in the stable version?

---

Separate from questions above: Does anyone else think it'd be nice to complete the "dates collection" also for the releases that happened prior to our GitHub move? I am sure we could find these dates from the Google Mail List or some other place and then add them manually?

**Comment by franklin-feingold** [comment]
> Ahh, I see: latest does behave like I would expect. The development version does not have a date, but all others do (since moving to GitHub).

Yup! It would make sense the development does not because it is the unreleased. 

> It's just a bit confusing that in the stable version, the date is not written for the most recent release. I.e., it will probably be written for our currently most recent v1.2.0 as soon as we make a new release, right? Do you know why this is the case?

Correct, so this flows onto how [the release protocol](https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md) is currently set up (this can be edited). Yes for the next version it will have the release date (from github) on dev's. This can be on the stable version by having it be part of the commits for the release PR. 

>Can you clarify what you mean by that? Is this a solution for writing the date of the most recent release even in the stable version?

Yes, this is how it would be able to be represented on the stable. Because the actual date of release could be unknown until it is ready to be merged. The PR author would submit a last commit to provide the date of release. So when it is merged and a github release is made, the date will be on the stable version. The stable version is whatever we have at the moment of a github release. AFAIK we can't go back in stable version to edit them.

**Comment by sappelhoff** [comment]
Closing, because this issue has been solved satisfactorily.

The only remaining bonus would perhaps be to add "post-hoc" the dates to all BIDS versions PRIOR to the move to GitHub, see [v 1.1.1](https://bids-specification.readthedocs.io/en/stable/CHANGES.html#111) and earlier
