### ISSUE TITLE
Use of acq parameter in MEG files

### ISSUE THREAD

**Issue by Moo-Marc** [bids-standard/bids-specification#212]
CTF MEG data acquisition allows saving two copies of the same data: one epoched and one continuous (with "AUX" added to the continuous file name).  We had been using the acq parameter to identify these duplicate raw datasets: ..._acq-AUX_...meg.ds.  I believe this falls under the proper intended usage of the acq parameter, and I'm not sure there's an adequate alternative if acq is removed.

**Comment by sappelhoff** [comment]
Tagging some MEG folks @robertoostenveld @monkeyman192

**Comment by robertoostenveld** [comment]
_Hmm, this brings back old memories when we also did this at the Donders. We now always use the epoched as pseudo-continuous with 10-sec segments, which (from interactions with CTF users elsewhere) seems to be common in other labs as well._

This might be a valid application. Searching my computer for examples, I found a short email thread from Feb 2018 with @guiomar, @sbaillet and Beth Bock where this was also discussed as such.

Right now it is not yet removed from https://github.com/bids-standard/bids-specification/blob/master/src/99-appendices/04-entity-table.md, but it optional for meg, and not allowed for channels/events. It should be properly documented, esp whether/how it affects the channels and events tsv files. 

E.g. is there one events file? Are those events timestamped relative to the recording, or relative to the samples in the MEG file (which I had always tacitly assumed, since I only considered (pseudo) continuous .ds datasets).
