### ISSUE TITLE
[INFRA] Latest version shows 1.2.0-dev

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#233]
In most cases the `-dev` suffix is considered pre-release state, so `1.2.0-dev` is for versions leading up to the 1.2.0 release. We are post-1.2.0, but the listed version is `1.2.0-dev`.

Do we consider this a problem?

**Comment by sappelhoff** [comment]
I consider this to be how it should be: Our most recent stable version is `1.2.0`, and the latest version is like `master`, which is where further `development` happens based on our most recent stable version --> `1.2.0-dev`.

Or should it be `1.3.0-dev`, because we are providing the development version of our upcoming release?

**Comment by effigies** [comment]
> Or should it be `1.3.0-dev`, because we are providing the development version of our upcoming release?

This is what I would expect from a [semver](https://semver.org/) perspective.

**Comment by sappelhoff** [comment]
+1 then to change this and also adjust it in the step 5 of the [release protocol](https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md)
