### ISSUE TITLE
Renaming files

### ISSUE THREAD

**Issue by kathy-snider** [bids-standard/bids-specification#282]
If we rename a file, we'd like to be able to point back to the original file in the metadata. Can we add a metadata field like SourceFile? 

Here's our situation:

We have multiple sessions that we would like to process as though it were a single session. To do this, we need to rename the files from ses-1_task-whatever_run-01 thru ses-n_task-whatever_run-0m into ses-all with tasks that match runs 0-m.  But we also want a way to reference the original files.

**Comment by sappelhoff** [comment]
Hi @kathy-snider - could you be a bit more specific?

from your example I get that you want to rename files in a BIDS dataset (not in `/derivatives` and not in `/sourcedata`).

--> Where do you want to put these files?

> we'd like to be able to point back to the original file in the metadata. Can we add a metadata field like SourceFile?

Do you have a specific metadata file in mind?

This seems to be more about data processing/analysis than about data storing. Do you HAVE to store the "combined files"? Or could you alternatively write code that reads your BIDS data, combines the files in a temporary directory, does the analysis, ... saves the results ... and deletes the temporary directory?

Or would this take too many resources for each analysis run?

**Comment by DimitriPapadopoulos** [comment]
@kathy-snider I see BIDS as a specification for storing and sharing “cold” and curated data - in the sense that data shall not change or not much - and not for “warm” data that is being processed. I wouldn't like the BIDS specification to support the details of data curation and processing.
By the way, why is the software unable to operate on the original file names? Have you written it? If so it might be worth adding an option to operate on multiple sessions.

**Comment by nicholst** [comment]
@kathy-snider I would also point you to BEP 15, defining mappings from existing data structures to BIDS.  It's not exactly what you're describing (and they're hasn't been much activity on it) but it seems related.

**Comment by satra** [comment]
> I see BIDS as a specification for storing and sharing “cold” and curated data - in the sense that data shall not change or not much - and not for “warm” data that is being processed. 

@DimitriPapadopoulos - we do "warm" use of bids routinely in ongoing projects, so i would not characterize BIDS as such.

@kathy-snider - the notion of a session is a logical one, typically with time as the variable. the ability to process runs/files appropriately does depend on the software you end up using. if the software is not BIDS compliant, you will have to do something to make it work. Using the BIDS layout to make the software work is not preferred compared to communicating to a new user of your dataset how the data were collected.

there are several examples of longitudinal data in openneuro and comprise missing values, different tasks on different days, etc.,.

**Comment by DimitriPapadopoulos** [comment]
@satra You're right of course. Perhaps the distinction is between data that should remain temporary and unpublished and final output we intend to keep and share. I just feel it's a bad idea to tweak BIDS for the purpose of facilitating the operation of specific scripts on "warm" data.

**Comment by kathy-snider** [comment]
So, I should have been more specific. 
First, this is not really about naming the files with BIDS names - we already have the BIDS input in BIDS format.
We have a pipeline that processed BIDS data, and we are adding an "all sessions" option, because we have neonates that cannot really do 1 long session. But we want to combine all of the sessions from a single day as though it were 1 session. We will have 1 set of anat data and probably 1 set of fmaps, but will have several sets of func data. The way the data is currently collected the func data will be named sub-X_ses-Y_task-rest_run-01 through sub-x_ses-y_task-rest_run-n for 1 session and then sub-X_ses-Z_task-rest_run-01 through sub-X_ses-Z_task-rest_run-m for the next. The sessions *may* be named in some kind of order (like by the time of day), but we cannot count on that. We would like make one session such that we combine one set of anat data, one set of fmap data (or, use the IntendedFor field if there is more than one set of fmaps) and one set of func data in which the runs are numbered 01 through n+m. I am writing a little app to do that for the user and to allow them to specify what order the  functional data will be in. 
Each of the func files has a json sidecar, and that is the metadata I'm asking about. We would just like the ability to point back to the original file, for bookkeeping purposes if nothing else. It is important to be able to get back to scanned data so that we know exactly how the data was processed from the  time at the scanner throughout the entire pipeline. If we don't keep the intermediate input files, and the pointers back to the originals, we will not know in what order those runs were processed.

**Comment by yarikoptic** [comment]
I would have done something like this:

1. used datalad to keep data under git/git-annex control
2. created a branch "original" (or something else) which would be that original layout
3. perfected the script you are talking about to re-layout the files ;-)
4. in "master" branch would keep the result of running your script on "original" branch layout, as recorded by "datalad run" in the git history

benefits:
- no wasted space.  Since git-annex uses symlinks, there will be clone to no additional space consumption across two layouts
- switching between those two layouts will be a breeze -- again, just symlinks
- `git diff` could still be used to see how branches are different.  So even though there would be no explicit metadata field added, full "provenance" would be available to figure out where it came from.
- `git log` on any moved file would show that it was the result from running that command

Re "cold" aspect mentioned above.  I was and will be fighting to claim that "any BIDS dataset is a  derivative dataset", in that it is not god's given and derived from somewhere.  A mere presence of `sourcedata/` guarantees that.  Because of that there nearly always be curation/fixing/changes.  And that is why we should adopt some parts of BIDS Derivative proposal into BIDS "core", e.g. to annotate in dataset_description.json how this BIDS dataset was obtained.  This use case is yet another nice example for that need.

**Comment by sappelhoff** [comment]
Just to follow up @kathy-snider did you end up using git-annex as @yarikoptic suggested? Or did you find another solution? 

Or is this still a hot topic and you need input that you have not yet satisfactorily received?
