### ISSUE TITLE
Auto generate change log

### ISSUE THREAD

**Issue by chrisfilo** [bids-standard/bids-specification#3]
Based on pull requests. Listed on github via releases.

**Comment by franklin-feingold** [comment]
Starting to work on this - @teonbrooks @choldgraf may you have any recommendations to create this automated solution? Any suggestions will be greatly appreciated!

**Comment by emdupre** [comment]
Have you already looked at [release-drafter bot](https://github.com/apps/release-drafter) ?

**Comment by franklin-feingold** [comment]
Thank you for the recommendation! This looks like a good option. It appears that it will output onto the releases tag? The hope is that the merged PR's will be automatically added to the CHANGES.md, with the CHANGES.md linked in the readthedocs.

**Comment by emdupre** [comment]
It _will_ output to the release notes ! You can see them as a draft before the release, looking something like this:

![screenshot from 2018-11-07 20-01-30](https://user-images.githubusercontent.com/15017191/48171009-ffa25c80-e2c7-11e8-9561-fe5e07dc913a.png)


One thought: It looks like you're building your RTD site continuously, rather than only at releases. If that's true, then my concern would be that a continuously updating changelog (by directly adding merged PRs to a CHANGES.md) could yield confusion as to what is in the "beta" specification as opposed to the official release.

I _think_ the solution used in other software such as `FMRIPREP` (and I know the solution we use in `tedana`) is to manually update the changelog at releases. But I'm not sure what your considerations are for minting a release, here !

**Comment by emdupre** [comment]
Actually, that's a broader issue, then, if any merged PRs are going live on the specification as soon as they're merged. Maybe the docs *should* only be built at releases ? Or I might just have totally misunderstood the current situation, sorry !

**Comment by emdupre** [comment]
Yes, I'd +1 having RTD build `stable` ! AFAICT that's not where we are currently, but it would make it much easier to keep track of changes between releases as PRs are merged in.

That being said, it won't solve your question @franklin-feingold, of having the CHANGES.md file automatically update as well. Manually pulling from the drafted release notes is one option, but there might be other, better ones !

**Comment by franklin-feingold** [comment]
Thank you for your explanation @emdupre ! Very useful to know about that tool and this possible solution moving forward. I will continue looking for other possible solutions that may update directly into the CHANGES.md file.
