### ISSUE TITLE
participants_id nomenclature

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-specification#384]
I'm wondering whether we shouldn't rename the `participants_id` key and even the participants notion throughout BIDS to `subject`. For all data I have seen these fields end up having the same value as `subjects`, and even if somewhere they might not, I don't think it makes sense to encourage two value sets specifying the same entities.

**Comment by chrisgorgo** [comment]
The term "participant" was used out of respect for study volunteers, but unfortunately, that was a last-minute change and not everything was converted (for example `sub` prefix) due to omission.

Changing this now would lead to a lot of compatibility issues. I'm not sure the benefits would justify it.

**Comment by TheChymera** [comment]
Adding to that, the “respect” considerations specific to human subjects don't generalize well to neuroimaging research as a whole. We're trying to improve BIDS usability for preclinical neuroimaging (with some success), and calling mice “participants” is weird and possibly confusing (the participants of a clinical study are the operators). Not least of all, for privacy concerns, I assume human subjects get alphanumeric identifiers. I think “respect” becomes an inappropriate notion at that point.

The backwards compatibility issue makes sense, yes. Is there no policy for introducing backwards-incompatible changes? In my data I add a separate identical column to `participants_id` called `subject`, in order to remain BIDS-compliant but not have to use confusing nomenclature. I think it's an appropriate solution for a transition phase.

**Comment by sappelhoff** [comment]
> The term "participant" was used out of respect for study volunteers, but unfortunately, that was a last-minute change and not everything was converted (for example sub prefix) due to omission.

Ahh I have always wondered about this.

@TheChymera I think you make fair points about having `subjects` consistently instead of `participants`, but I don't think this change has a place in BIDS 1.X for the often mentioned compatibility reasons.

> Is there no policy for introducing backwards-incompatible changes?

There is an official strict policy that we don't implement backwards-incompatible changes (see first sentence  [in the BEP part of the spec](https://bids-specification.readthedocs.io/en/stable/01-introduction.html#extensions)).

All proposals for BIDS 2.0 (which WILL have backwards INcompatible changes) are collected here: https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw

Please feel free to add your proposal!

**Comment by TheChymera** [comment]
I couldn't figure out how to link to a text anchor in Google Docs, here is the proposal text I added:

>Homogenize “Subject” Nomenclature
>
>We are currently using the terms “participant” and “subject” interchangeably. I propose we make the names homogeneous. In order to afford better extendability with preclinical research, the term “subject” would be significantly more apt.
>GitHub Issue: https://github.com/bids-standard/bids-specification/issues/384
>
>This change would include renaming the `participants.tsv` file to `subjects.tsv`, and the `participant_id` column in said file to `subject`.

**Comment by effigies** [comment]
Link: https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw/edit#heading=h.ai8idsat628d

**Comment by sappelhoff** [comment]
closing this here, the discussion can continue in the BIDS 2.0 document. Thanks for adding it there @TheChymera
