### ISSUE TITLE
Link Checker broken due to excessive requests to GitHub

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#474]
GitHub seems to be rate-limiting requests, and we're now getting a lot of results like:

```
URL        `https://github.com/bids-standard/bids-specification/pull/13'
Name       `#13'
Parent URL file:///root/build/site/CHANGES.html, line 1067, col 41
Real URL   https://github.com/bids-standard/bids-specification/pull/13
Check time 0.397 seconds
Size       1KB
Result     Error: 429 too many requests
```

See, for example, https://app.circleci.com/pipelines/github/bids-standard/bids-specification/1076/workflows/7acda833-9ecf-4c1a-a6f7-51f45641fbc1/jobs/2434.

We're running it twice, though I don't understand the explanatory comment:

https://github.com/bids-standard/bids-specification/blob/8a174714ed8751daf1b7b26628f441481042836b/.circleci/config.yml#L42-L45

@yarikoptic Any thoughts? Maybe we can adjust the commands to ensure there's no duplication? If linkchecker could output a list of targets that could be combined and deduplicated, that might be a useful approach.

**Comment by yarikoptic** [comment]
well, we could make use of `--ignore-url=` (could be used multiple times) to just ignore all github urls may be and assume that they are correct? ;)

re twice: indeed I should have been more descriptive.  My guess is that the first run validates "relative" urls being correct - it shouldn't query external sites so should not cause double checking of github etc.  The second one -- would go through external urls but since all local ones were verified -- would ignore `file://`.

**Comment by effigies** [comment]
Maybe we should start by blacklisting `https://github.com/bids-standard/bids-specification/issues/*` and  `https://github.com/bids-standard/bids-specification/pull/*`, to cover the changelog entries.

> re twice: indeed I should have been more descriptive. My guess is that the first run validates "relative" urls being correct - it shouldn't query external sites so should not cause double checking of github etc.

Got it.

**Comment by yarikoptic** [comment]
keeps coming up, I will now quickly furnish a PR to exclude https://github.com/bids-standard/bids-specification/pull/ etc
