### ISSUE TITLE
Clarify MRI centric language: special duration "0" in events files

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#498]
[`events.tsv` files have a `duration` column specified in seconds.](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/05-task-events.html#task-events)

The value `0` takes on a special meaning:

> A "duration" value of zero implies that the delta function or event is so short as to be effectively modeled as an impulse

Can we find a language that generalizes to electrophysiology datasets? Or is this concept not applicable to MEG/EEG/iEEG and it's fine to have this part of the spec for `duration` only refer to MRI?

**Comment by effigies** [comment]
Could you clarify what is problematic here? This language is not MRI-specific as far as I can tell.

* [Impulse response](https://en.wikipedia.org/wiki/Impulse_response)
* [Dirac delta](https://en.wikipedia.org/wiki/Dirac_delta_function)

**Comment by sappelhoff** [comment]
It may be that my knowledge is limited here, but in MEEG we usually don't "model an event", rather we use the event onsets and cut out a time window relative to the onset (called an epoch).

What's more relevant about onset and duration is, that:

- at the onset of a stimulus, there will be a strong visual response in the brain
- at onset+duration (=offset of the stimulus), when the stimulus "disappears" from the screen there will again be a relatively strong visual response in the brain (relative to "no change")

So I am not sure, but perhaps then a duration of `0` in terms of MEEG could mean that a stimulus is very briefly flashed ... so that the strong visual response to the appearance of a stimulus has no time to "return to baseline" before the stimulus disappears again. 

Sorry for being unclear on this - I just had the feeling that this definition could be improved. Mainly because I have no idea what to do with it in an MEEG context.

@robertoostenveld are you happy with it?

**Comment by satra** [comment]
@sappelhoff - agreeing with @effigies here. it's a very specific notion to indicate that something can be modeled as an impulse. however, what can be modeled as an impulse is domain specific and left to the user.

so in the MEEG case you could model onset and offset as separate events and the entire stimulus as a third event if you choose to. alternatively, you can simply model the actual stimulation, i.e. onset + duration, and leave it to some downstream software to determine onset and offset as alignment times.

in most cases, whether mri or eeg, i would expect duration to be non-zero, but there are many situations, where the duration is indeed too small relative to signal sampling rate and could be left as 0 (e.g. a binaural audio experiment where the stimulus is a lateralized click in micro seconds). 

iirc, in bids it was introduced to be backwards compatible/supportive of imaging studies where the event durations were not captured.

**Comment by robertoostenveld** [comment]
I had read this section before, wondered about it shortly, and then considered it ok and moved on. 

The way I read it is that "modeled" does not specifically relate to the analysis strategy that is employed on the brain signals (like GLMs), but to the event. E.g. an auditory click, but also a median nerve electrical pulse, a short visual stimulus (one or a few frames), or the click moment of the button press. Depending on how you consider it, the latter ones are not particularly short (you cannot press a button in a microsecond, it takes >10ms). It is indeed specific to the recording system combined with characteristics of the brain physiology that is recorded.

The way that most MEG/EEG systems are used, the duration of the stimulus is transmitted from the presentation computer to the recording system and hence not coded in the file itself, but only the onset (and "value") of the stimulus. Most TTL level triggers from a presentation computer that are sampled with an 8- or 16-bit digital interface on the MEG/EEG system are short, but long enough (e.g. 10 ms) so that they are properly sampled. But the duration of the trigger is not interesting since it does not relate to the brain, nor to the stimulus itself.

If you really get into the details (like in [`ft_read_event.m`](https://github.com/fieldtrip/fieldtrip/blob/master/fileio/ft_read_event.m) and the underlying [`read_trigger.m`](https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/read_trigger.m), then it gets complicated and you need to know hardware details (like is it the upgoing or downgoing flank, whether there are transient sampling effects to be expected on the digital channel) but also usage details (is the TTL value sent as a "trigger" at onset and another at offset, or is the TTL signal a "gate" that high all the time during stimulus presence), what is the delay of the audio card and speakers that are at a distance with sound traveling at 3ms per meter, etc.)

I think that the current specification is good enough. There are no events or stimuli where the duration is infinitely short if you really look at it in detail. Nevertheless, we ignore the duration. I would also consider it fine if the `duration` column were optional, where its absence indicates that the duration of all events is not relevant or zero (e.g. when the onset corresponds to the trigger moment). This is how most EEG processing uses it anyway. 

What is problematic, now that I re-read the section, is that for sample it is not specified whether it is 0- or 1-offset.

**Comment by sappelhoff** [comment]
Okay, thanks a lot for your input Chris Satra and Robert. I can close this issue now.

> What is problematic, now that I re-read the section, is that for sample it is not specified whether it is 0- or 1-offset.

ugh, yes. I remember we discussed this but apparently we forgot to write it down. I'll open an issue for this.
