### ISSUE TITLE
Table fences in PDF of specification misaligned

### ISSUE THREAD

**Issue by VisLab** [bids-standard/bids-specification#549]
PDF version 1.4.0 of read-the_docs --- a number of the tables are messed up   
For example, on pages 13, 28, 30

**Comment by sappelhoff** [comment]
Thanks for the report --> you are probably referring to the PDFs of the spec hosted on zenodo: https://zenodo.org/record/3890439

Just FYI: These PDFs have nothing to do with readthedocs. We build them using pandoc and a python script by @Arshitha, see: https://github.com/bids-standard/bids-specification/tree/master/pdf_build_src

If somebody who reads this has time to look into this, it'd be much appreciated.

**Comment by sappelhoff** [comment]
thanks for looking into this @sebastientourbier! Would you be up to trying a fix?

**Comment by sebastientourbier** [comment]
@sappelhoff Yes I would be up to. 
Just to make sure I proceed correctly:
I am gonna pull the latest version of the master branch on my fork, create the branch fix_tables_in_generated_pdf, fix the tables and as soon all tables are fixed, I will open a PR to the master branch.
Is that correct?

**Comment by sappelhoff** [comment]
yes, sounds correct :+1: looking forwards to it

**Comment by sebastientourbier** [comment]
List of tables with problematic layout:
* page 13 (Tabular files)
* page 18-19 (Derived dataset and pipeline description)
* page 27-28 (Anatomy imaging data)
* page 29 (Task (including resting state) imaging data)
* page 30 (Required fields)
* page 37 (Sidecar JSON (*_meg.json))
* page 40 (Channels description (*_channels.tsv))
* page 43 (Fiducials information:)
* page 47 (Sidecar JSON (*_eeg.json))
* page 50 (Channels description (*_channels.tsv))
* page 56 (Sidecar JSON (*_ieeg.json))
* page 59 (Channels description (*_channels.tsv))
* page 76 (Common file level metadata fields)
* page 77 (Spatial references)
* page 79 (Preprocessed, coregistered and/or resampled volumes)
* page 81 (Masks)
* pages 94-95 (Appendix IV: Entity table)
* page 104 (Standard template identifiers) - ok but 1st column tight
* page 106 (Nonstandard coordinate system identifiers)
* page 106 (Non-template coordinate system identifiers)

**Comment by sappelhoff** [comment]
good idea, you can use a syntax like this: `- [ ] to be checked` to format interactive check mark boxes. That may come in handy to keep track which ones are fixed and which ones are not. They can be checked by clicking on them after the post is done. Or you can initialize them in checked mode using this syntax: `- [x] checked `

- [x] this one
- [x] this one too
- [ ] this one not

**Comment by sappelhoff** [comment]
@sebastientourbier I just realize: Please don't work on the `pages 94-95 (Appendix IV: Entity table)` because soon this table will be auto-generated, see: #475 

this is also good to keep in mind when writing the script for auto-generation @yarikoptic @tsalo --> if we can find a rule on how to write markdown tables that get properly rendered as PDF using pandoc, we should encode that rule within the auto generation scripts.

**Comment by Arshitha** [comment]
@sebastientourbier Thank you for looking into it. I believe this happens after each new release because of the column width mismatch. For this to work, like @sappelhoff suggested having some rules about writing markdown tables might be the quickest fix. However, in order to automate it using just the current script, I had a couple of ideas that I'll try out over the weekend and keep y'all posted.

**Comment by sappelhoff** [comment]
@Arshitha thanks for chiming in!

Are you suggesting that the fixes @sebastientourbier is doing currently will be undone at the next release? How so?

**Comment by Arshitha** [comment]
@sappelhoff Nope, I wasn't commenting on @sebastientourbier fixes coz I assumed he'd be working on fixing the column width proportions by programmatically calculating and adding the required number of `-`'s wherever required. But he plans to go into the .md files and fix the pipe tables manually by extending the column widths then it'll break during the next release. Because I'd fixed the tables manually by adding more `-`'s in the .md files

**Comment by Arshitha** [comment]
I was just saying that this might be a quick fix: 

> this is also good to keep in mind when writing the script for auto-generation @yarikoptic @tsalo --> if we can find a rule on how to write markdown tables that get properly rendered as PDF using pandoc, we should encode that rule within the auto generation scripts.

as you mentioned above

**Comment by Arshitha** [comment]
One of the ways I'm thinking of fixing this issue is by finding tables in .md files and calculating the maximum character count in each column (for each table) and then replacing existing table fences with reformatted (basically more `-`'s) fences. 

This might be a more long term solution because: 
1. Authors editing or adding new .md files don't have to worry too much about formatting tables 
2. Doesn't in any way affect rendering in `readthedocs` version 

I haven't had a chance to try it out but theoretically, I believe, this should work.

**Comment by Arshitha** [comment]
Okay, I just saw the PR #553  and it seems like he fixed it manually.

**Comment by sappelhoff** [comment]
> But if he plans to go into the .md files and fix the pipe tables manually by extending the column widths then it'll break during the next release. Because I'd fixed the tables manually by adding more -'s in the .md files in one of the previous release

I am just not sure how the breakage would happen during a release :thinking: 

> One of the ways I'm thinking of fixing this issue is by finding tables in .md files and calculating the maximum character count in each column (for each table) and then replacing existing table fences with reformatted (basically more -'s) fences.

that sounds nice indeed ... and the plus side would also be that we don't have to have the custom more wide table syntax in our source ... because it'll get generated / edited during the build only 

and for this automation script, you wouldn't have to think about aligning the table fence pipes `|` either, because that's only stylistic and should not affect the rendering

**Comment by sebastientourbier** [comment]
When checked on readthedocs, it seems it did not affect the rendering. 
But by going into this fences alignment problem, it also came to my mind that an automated way of fixing tables would be more ideal. So we should indeed correct the tables at two levels:
1. To make pandoc happy (PDF generation), we need to make sure that:
  1. proportion of -'s in first column and 
  2. the corresponding number of -'s should be bigger that the number of characters max in the first column
2. To make sphinx/readthedocs and so TravisCI happy (online doc), we need to make sure that after step1 each row has fences aligned to the fences in the row with -'s
