### ISSUE TITLE
--bids-filter-file seems not working as supposed

### ISSUE THREAD

**Issue by GongZhengxin** [bids-standard/bids-specification#723]
tried to only run files in session **ses-LOC** with **task-retinotopy**, I write my Filter.json as:

> {
> "t1w": {
> "datatype": "anat",
> "session": "ImageNet02",
> "acquisition": null,
> "suffix": "T1w"
> },
> "bold": {
> "datatype": "func",
> "session": "LOC",
> "task": "retinotopy",
> "suffix": "bold"
> }
> }

Becasue the doc on this method is sort of ambiguous to me, I am not sure about it. And my cml follows:

`$ fmriprep-docker $bids_fold $out_dir participant \ 
    --skip-bids-validation --participant-label core02 \ 
    --bids-filter-file $home/Filter.json \ 
    --fs-license-file $license_file \ 
    --output-spaces anat MNI152NLin6Asym:res-2 fsLR \ 
    --cifti-output 91k -w $work_dir `

But fmriprep actually loading all the existed files in all session folds with all task labels, it really bothers me a lot.

BTW few more questions on fmriprep:
when **--use-aroma** is set on, the fmriprep cifti output will generated by which of the volume datas? (i.e. The denosied one **~desc-smoothAROMAnonaggr_bold.nii.gz** or the couterpart **~desc-preproc_bold.nii.gz**?)

**Comment by tsalo** [comment]
Hi @GongZhengxin. It looks like this issue is tied to fMRIPrep, rather than the BIDS specification. Is that correct?

Unfortunately, we can't transfer issues across organizations (fMRIPrep is under the `nipreps` organization), so I think the best option is to close this issue and open a fresh one in the [fMRIPrep repo](https://github.com/nipreps/fmriprep/issues).

**Comment by effigies** [comment]
Yes, please reopen at fMRIPrep. Closing here.
