### ISSUE TITLE
affine transformation matrix to map MEG space into defaced MRI

### ISSUE THREAD

**Issue by guiomar** [bids-standard/bids-specification#752]
Hi!

Talking to @RikHenson, we were wondering if there's a specific place in the specs to store the affine transformation matrix that maps MEG space to defaced MRI. I suggested to store the `HeadCoilCoordinates`, `AnatomicalLandmarkCoordinates` and `DigitizedHeadPoints` in the ***_coordsystem.json**. But how about this matrix?

Rik refers to a 4x4 (or 3x3 if same resolution) affine transformation matrix that maps from the MEG space to MRI space (or vice versa), ie created after coregistering the headpoints+fiducials to the MRI scalp surface. While some people coregister using only the fiducials, others also use headpoints to help with any error in the fiducial locations. This coregistration can be difficult if the headpoints include digitised points on the nose, when the nose is not present in the MRI surface because of **de-facing**. So he was planning to do the coregistration on a local (non-shared) version of non-defaced MRIs, and provide the transformation matrix for other researchers when we share a (BIDS) version in which the MRIs have (necessarily) been de-faced. What would you recommend?

Could this be related to the extension for affine transformations BEP014?
https://docs.google.com/document/d/11gCzXOPUbYyuQx8fErtMO9tnOKC3kTWiL9axWkkILNE/edit#heading=h.wo1gx72glci0

@robertoostenveld @sappelhoff @agramfort @ftadel @Moo-Marc @jasmainak

**Comment by Moo-Marc** [comment]
Hi Guio,

I started basically the same discussion on the google group: https://groups.google.com/g/bids-discussion/c/BeyUeuNGl7I 

We don't need to save an additional matrix, as long as we assign the "fitted" landmark coordinates either in the _t1w.json (the "MNE approach") or the _coordsystem.json (my suggested "Brainstorm approach").  But I agree it would be best to standardize, in particular so that software tools know how to best import this data (and in particular don't re-do head point fitting on the defaced anatomy).

Cheers,
Marc

**Comment by guiomar** [comment]
Thanks Marc!! I hadn't seen the discussion on the google group
