### ISSUE TITLE
Pet template file names issue in bep009 1.6.0-dev rendered draft

### ISSUE THREAD

**Issue by chrisrj** [bids-standard/bids-specification#768]
Hello,
If I am not mistaken, in early 2021, the PET template file name changed
from sub-<label>[_ses-<label>][_task-<label>][_acq-<label>][_rec-<label>][_run-<index>]_pet.json
to sub-<label>[_ses-<label>][_task-<label>][_trc-<label>][_rec-<label>][_run-<index>]_pet.json
that is the '_acq' key label was renamed '_trc'.
Currently, the PET template file name in 09-positron-emission-tomography.md
is generated by a macro {{ MACROS___make_filename_template(datatypes=["pet"], suffixes=["pet"])
On the draft https://bids-specification.readthedocs.io/en/bep-009/04-modality-specific-files/09-positron-emission-tomography.html, this is rendered as
sub-<label>[_ses-<label>][_task-<label>][_acq-<label>][_trc-<label>][_rec-<label>][_run-<index>]_pet.json
with both a_'acq' and a '_trc' key label.
Best regards,
Christian

**Comment by tsalo** [comment]
Thanks for reporting this. Two questions:

1. Should this extend to `blood.tsv` files as well? Currently both `acq` and `trc` are allowed.
2. Can you think of any cases where a generic label (i.e., `acq`) could be useful for either `pet.nii.gz` or `blood.tsv` files? We allow `acq` for most files in BIDS because it serves as a freeform label, but if `trc` and other entities cover all of reasonable cases for PET I can remove it.

**Comment by effigies** [comment]
I would vote to drop `acq` unless someone can identify an acquisition parameter variation that isn't already covered by `trc-` and `rec-` for PET or `recording-` for blood. We can re-add entities in later releases if the example comes later.

Come to think of it, for passive recording techniques, including MEG and iEEG, there's limited scope for varying acquisition parameters. Would need to be BIDS 2, but we might want to consider removing that. EEG might have more need because of the variability of electrode placement.

**Comment by mnoergaard** [comment]
Thanks for reporting this @chrisrj. Based on previous discussions regarding this the `trc` was meant to replace the `acq`. This is also how the validator has been made. This applies both to pet files and blood files.

**Comment by tsalo** [comment]
I can open a PR to drop `acq` from both `pet.nii.gz` and `blood.tsv` files. We can also double-check the other entities in use in the pull request review.

**Comment by tsalo** [comment]
Not sure why #769 didn't close this, but I'm going to close now that the PR has been merged. @chrisrj please reopen if the problem wasn't resolve, or open a new issue if you identify any other issues with the schema/rendering in BEP-009.
