### ISSUE TITLE
Adding BDF and BDF+ to the acceptable data formats for eeg/ieeg data

### ISSUE THREAD

**Issue by Aaronearlerichardson** [bids-standard/bids-specification#821]
BDF is a "24-bits version" of the currently preferred 16-bit EDF format. Should this be added to the currently accepted file formats? 

A more detailed description of the new format can be found [on this website](https://www.teuniz.net/edfbrowser/bdfplus%20format%20description.html)

**Comment by sappelhoff** [comment]
Thanks for raising this point @Aaronearlerichardson.

I think it's a shortcoming of the EEG spec to mention EDF and BDF, but being unclear about whether their "natural" extensions are permitted (EDF+ and BDF+, which share the same extension: `.edf` `.bdf`).

- [Link to source](https://github.com/bids-standard/bids-specification/blame/master/src/04-modality-specific-files/03-electroencephalography.md#L26-L36)
- [Link to docs](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html)

In my mind, EDF+ and BDF+ are supported, especially because virtually all software that supports EDF/BDF also supports EDF+/BDF+. 

I suggest that we clarify this in the specification, but we at least the BEP leads of EEG/iEEG and preferably a couple more community members to chime in on this.

I focused these points on EEG. But in iEEG we have a similar problem: "EDF" is advertised, but no point is being made about "EDF+". In accordance with EEG, I suggest that we clarify that EDF+ is also permitted.

In contrast to EEG, BDF/BDF+ are not permitted in iEEG and that'll probably stay this way.


cc @dorahermes @choldgraf  @robertoostenveld @CPernet

**Comment by CPernet** [comment]
I suppose the advantage is that the time stamp allows better synch or separate modalities - so I'm ok with that.  Otherwise, other 'stuff' should be stored as separate files anyway.

as for precision the brain vision format works fine - why would we need BDF+ for that (allowed anyway, although not officially supported) ; but anyway EEG multimodal is really important so the + is good for that

**Comment by robertoostenveld** [comment]
I am not aware of any formal specification of a BDF+ file format, hence I would not consider it supported per see. There is this https://www.biosemi.com/faq/file_format.htm, and there is this https://www.edfplus.info/specs/edfplus.html, but not the combination of the two. 

I also don't know if it is supported by any BIDS-compatible analysis software, although...  A file that is in EDF+ format can AFAIK also be read by EDF-only compatible software (except that the annotations channel will not be interpreted and appear as gibberish). If the same is the case for the BDF+ format, then I don't see a problem having a BDF+ file in a BIDS dataset, since it would also be a BDF file, and the annotations must be in the `events.tsv` file anyway.

**Comment by sappelhoff** [comment]
> I am not aware of any formal specification of a BDF+ file format, hence I would not consider it supported per see. There is this https://www.biosemi.com/faq/file_format.htm, and there is this https://www.edfplus.info/specs/edfplus.html, but not the combination of the two.

see: https://www.teuniz.net/edfbrowser/bdfplus%20format%20description.html

>  A file that is in EDF+ format can AFAIK also be read by EDF-only compatible software (except that the annotations channel will not be interpreted and appear as gibberish). If the same is the case for the BDF+ format, then I don't see a problem having a BDF+ file in a BIDS dataset, since it would also be a BDF file, and the annotations must be in the events.tsv file anyway.

Teuniz says:

>  BDF+ is compatibel with BDF. BDF+ files can be read and processed by older BDF software.

**Comment by robertoostenveld** [comment]
Sorry, I did not read the original https://github.com/bids-standard/bids-specification/issues/821#issue-919197778, only the reply in which I was mentioned. It points to a specification, and lists one software package in which it is supported (EDFbrowser). My other arguments remain as they are.

**Comment by robertoostenveld** [comment]
A related question to consider with the BIDS specification w.r.t. file formats that evolve into new versions: is [NIFTI-2](https://brainder.org/2015/04/03/the-nifti-2-file-format/) supported?

**Comment by effigies** [comment]
> A related question to consider with the BIDS specification w.r.t. file formats that evolve into new versions: is [NIFTI-2](https://brainder.org/2015/04/03/the-nifti-2-file-format/) supported?

I would expect NIFTI-2 to be valid BIDS, since it has pretty much universal support among neuroimaging tools, but I don't know if the validator supports it.
