### ISSUE TITLE
multiple acquisitions

### ISSUE THREAD

**Issue by Lolibike95** [bids-standard/bids-specification#940]
Dear all,

I am about to make the BIDS renaming, but I have 2 issues:
1) multiple acquisitions: should I rename all the files? let's say I acquired the same sequence twice, but the second is the good one. Should I rename both, or the second one is enough?
2) partial acquisitions: in case the number of files I have is partial (let's say, in case of DWI I have 4 files instead of the correct number, that should be 8): in this case should I rename them or is this not necessary (i.e., I will not send my data anywhere)?

**Comment by sappelhoff** [comment]
Hey @Lolibike95 your question sounds more like a "usage" question rather than a problem with the specification itself, or a proposal to change it.

Usage questions on BIDS are best handled over at Neurostars, with the BIDS tag: https://neurostars.org/tag/bids

You are more likely to get helpful answers there.
