### ISSUE TITLE
BIDS VFA anat datatype entry.

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-specification#977]
Is it an ommission that this variation of the `anat` datatype: https://github.com/bids-standard/bids-specification/blob/master/src/schema/rules/datatypes/anat.yaml#L147
does not list VFA as a possible suffix?

**Comment by tsalo** [comment]
VFA is described in another part of that file. I believe that the suffix group "VFA + MT" refers to files derived from protocols with varying flip angle _and_ a magnetization transfer pulse, rather than just varying flip angle, as in the VFA suffix. However, that's something that a qMRI-BIDS person would probably know more about.

**Comment by TheChymera** [comment]
@tsalo thanks for the update. Is there anybody whom we could ping for that? just asking since I came across some VFA data with an echo entity, and am unsure whether this is an omission in BIDS, or some issue with the data naming. The comment on the line linked above made me think the former might be a distinct possibility.

**Comment by TheChymera** [comment]
@effigies should I submit a PR, or does this still need review?

**Comment by agahkarakuzu** [comment]
@effigies I don't see any issues in adding echo optional to VFA, as long as it is not going to be mixed up with an existing file collection. 

It is worth noting that VFA is not sequence specific. But (MT + VFA) cases in BIDS are sequence specific (e.g. MPM).
