### ISSUE TITLE
Microscopy files of suffix `_photo` do not support a `_run-` entity.

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-specification#992]
This seems like an artificial limitation, while the usefulness of doing this is indeed debatable, multiple runs can always come with multiple photos. Should I just sumbit a PR?

**Comment by Remi-Gau** [comment]
Not opposed to the idea of having an additional optional entity. 

@mariehbourget what do you say?

**Comment by mariehbourget** [comment]
Hi @TheChymera and @Remi-Gau,

This is a very interesting question!

I'm not sure that we interpret "run" in the same way.
In BIDS a "run" is used to represent multiple acquisitions with the exact same parameters in the same session. My understanding is that those parameters include the modality suffix (`SPIM`, `SEM`, `photo`, etc).

For example with:
```
sub-01_sample-01_run-01_photo.jpg
sub-01_sample-01_run-02_photo.jpg
```
In this case, "run" means "second acquisition (run) of the photo" and does not mean "photo of the second acquisition (run)".

In the spec, the idea is to use "acq" with a descriptive enough label to distinguish between multiple photos of the same sample (example [here](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/10-microscopy.html#photos-of-the-samples-_photoextension)).
Again, "acq" refer to the acquisition of the photo itself and does not refer to the "acq" of the same sample with another modality suffix.

I hope my explanation is not more confusing, let me know if that is not clear.
The implementation of "photo" is similar to other modalities (ex: [meg](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#landmark-photos-_photojpg) and [ieeg](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/04-intracranial-electroencephalography.html#photos-of-the-electrode-positions-_photojpg)) if that helps.

**Comment by satra** [comment]
thank you @mariehbourget . there are indeed two levels of multiplicity. 

1. multiple acquisitions of the photo associated with a "run": in such a case `acq` should be used, not `run`

2. multiple `runs` of microscopy acquisition: for microscopy, one may acquire the same sample multiple times (before after clearing and restaining, or simply multiple acquisitions) and this would constitute multiple `run`s. if there was a photo taken before each of these, then `run` could be part of photo. thus `run` should only be included if the files it relates to have multiple `run`s. i believe this is where `run` itself would be needed.


i think this is different from @mariehbourget 's view, hence bringing up the two possibilities.

**Comment by mariehbourget** [comment]
Thank you @satra, I agree with point 1.

Point 2 is more ambiguous:
- "run" is supposed to be used "If more than one run of the same sample, acquisition and stain are acquired during the same session"
- "acq" is used as "a custom label that MAY be used to distinguish a different set of parameters used for acquiring the same modality"

In the case you described above:
- "before after clearing and restaining" would be described in "acq" (and potentially "stain")
- "simply multiple acquisitions" would be described in "run"

I'm not against adding "run" to the "photo" suffix but I think it may be more ambiguous and would diverge from the current definition, because "run" is an attribute or the "imaging file" and not of the "imaging experiment".

Let's say we have 2 runs of 2 different modalities (`SPIM` and `OCT`):
```
sub-01_sample-01_run-01_OCT
sub-01_sample-01_run-02_OCT
sub-01_sample-01_run-01_SPIM
sub-01_sample-01_run-02_SPIM
```
Unless I'm mistaken, BIDS doesn't assume that the "run-02" for OCT is the same that the "run-02" for SPIM (or I can't find where that would be specified).
So if we would add `sub-01_sample-01_run-02_photo`, my understanding is that the `run-02_photo` is not necessarily linked with the `run-02_OCT` or `run_02_SPIM`.
If I understand correctly, `photo` would be "just" another modality with its own set of runs.

I think if one wants to "link" a photo to a specific run, it would need to be something like this (2 runs of SPIM and 2 photos each):
```
sub-01_sample-01_acq-run01spim01_photo.jpg
sub-01_sample-01_acq-run01spim02_photo.jpg
sub-01_sample-01_acq-run02spim01_photo.jpg
sub-01_sample-01_acq-run02spim02_photo.jpg
```

**Comment by satra** [comment]
> BIDS doesn't assume that the "run-02" for OCT is the same that the "run-02" for SPIM 

those are independent suffix entities, and indeed there is no current correspondence. however, my understanding is that `_photo` is more analogous to `_events.tsv` in bold fmri, one that augments the information about a specific acquisition rather than being independent from it. however, see below.

overall i think there are a few questions: 
- photos may be sample and imaging type specific, as well as the ease of capturing it may mean multiple instances. 
- acquisition can be easily overloaded to mean anything and in bids we have tried to restrict this a bit
- if we stay with `acq`, then `IntendedFor` would be a good metadata field to have in the corresponding photo json file. if the photo applies to multiple different acquisitions like OCT and SPIM, this would cover that scenario whereas simply using name/run won't work.

ok, i'm more convinced that `run` doesn't solve the problem, `acq` is sufficient, but we should add the `IntendedFor` keyword for the json metadata of a photo.

**Comment by mariehbourget** [comment]
Thank you @satra and @TheChymera  for your feedback and brainstorm on this.

I'm not familiar with the `IntendedFor` field and I'll look into this a little bit more to see how it could work (or already works?) with imaging file (not tsv).
Also, I just realized that photo files don't have any associated JSON files at the moment. So, contrary to what I previously said, it might not be "just another modality". But I agree that it is a separate issue.

For the "run" entity in "photo" file, I'm not against it per se, but I think we would need a clear definition to avoid ambiguity.

I see 3 options:
1. Status quo: Any "link" between another modality run and a "photo" run could be expressed in the "acq" label (which is sufficient for the moment but may not be optimal).
2. "run" is added to photo with the same definition as the rest of BIDS i.e. "second acquisition of the photo".
3. "run" is added to photo with a definition implying that it means "photo associated with run-XX" of another modality.

If I understand correctly, the option 3 was the idea behind opening this issue.
I would like to more feedback from the maintainers on this, what do you think @Remi-Gau?

**Comment by Remi-Gau** [comment]
> I'm not familiar with the `IntendedFor` field and I'll look into this a little bit more to see how it could work (or already works?) with imaging file (not tsv). Also, I just realized that photo files don't have any associated JSON files at the moment. So, contrary to what I previously said, it might not be "just another modality". But I agree that it is a separate issue.

>     1. Status quo: Any "link" between another modality run and a "photo" run could be expressed in the "acq" label (which is sufficient for the moment but may not be optimal).

Not a big fan of this one, because unless we provide clear guideline of how to express the `acq` label then things can get messy. And people can always ignore guidelines of make their own rules.

>     2. "run" is added to photo with the same definition as the rest of BIDS i.e. "second (third, fourth, etc) acquisition of the photo".

But then we lose the potential link that exists between the photo and the data file it associated with.

>     3. "run" is added to photo with a definition implying that it means "photo associated with run-XX" of another modality.

That leads to a redefinition of the meaning of `run` in this case which would be preferable to avoid.

> If I understand correctly, the option 3 was the idea behind opening this issue. I would like to more feedback from the maintainers on this, what do you think @Remi-Gau?

2 other possibilities:

1. `intendedFor` metadata field

2.  using the 'match' strategy used for physio file: https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/06-physiological-and-other-continuous-recordings.html

Option 1 allows a 1 to many mapping: a single photo can be linked to many data file.
Option 2 requires a 1 to 1 mapping.

Even though the example that gave rise to this issue seems to be OK to be handled with option 2, I suspect option 1 would give more flexibility.

**Comment by satra** [comment]
> I suspect option 1 would give more flexibility.

+1

**Comment by mariehbourget** [comment]
Thank you @Remi-Gau for the feedback.
Both you and @satra suggested the `IntendedFor` metadata field, and I agree that it seems the more flexible and reliable option to avoid redefining "run".

I will take a closer look into it tomorrow to see how it could be implemented. It will probably take some time because at the moment, the "photo" files don't have a sidecar JSON. So we would need to implement a "separate" JSON file specification for the "photo" files and add these new rules to the validator as well.

From my understanding, if we go with `IntendedFor`, "acq" is sufficient and we would not add the "run" entity to photo files. In that case, should we close this issue and open a new one for `IntendedFor` specifically?

(tagging @jcohenadad as well)

**Comment by mariehbourget** [comment]
I opened a PR (#1000) with the "IntendedFor" idea so we can get some more feedback.
I think it works pretty well. Let me know what you think, thank you!
